# This module is used to handle below data cleaning on the flattened restaurant data
   * Identify missing values
   * Replace missing values with relevant values
   * Convert Alphanumeric categorical values to Numerical values
   * Clean data with typos and bring in uniformity of values based on analysis in Tableau.

Importing the required packages

In [1]:
import pandas as pd
import numpy as np
import os
import json
import re

Setting the display options

In [2]:
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

Reading the flattened csv file into a dataframe for EDA 

In [3]:
businessDF= pd.read_csv('AZ_Restaurant_Final_data.csv', sep = ';', header = 'infer', index_col ='Unnamed: 0')

C:\Users\nishi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (62,63,64,65,66,67,68,69) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Displaying some values of the dataframe to understand the layout

In [4]:
businessDF.head()

business_id                          name  neighborhood  \
0  rDMptJYWtnMhpQu_rRXHng                    McDonald's           NaN   
1  1WBkAuQg81kokZIPMpn9Zg  Charr An American Burger Bar           NaN   
2  iPa__LOhse-hobC2Xmp-Kw                    McDonald's           NaN   
3  kKx8iCJkomVQBdWHnmmOiA          Little Caesars Pizza           NaN   
4  YhV93k9uiMdr3FlV4FHjwA               Caviness Studio           NaN   

                         address     city state  postal_code   latitude  \
0           719 E Thunderbird Rd  Phoenix    AZ      85022.0  33.607070   
1  777 E Thunderbird Rd, Ste 107  Phoenix    AZ      85022.0  33.607310   
2            1635 E Camelback Rd  Phoenix    AZ      85016.0  33.508765   
3           10720 E Southern Ave     Mesa    AZ      85209.0  33.394877   
4                            NaN  Phoenix    AZ      85001.0  33.449967   

    longitude  stars  review_count AcceptsInsurance AgesAllowed   Alcohol  \
0 -112.064382    1.0            10              NaN         NaN      none   
1 -112.063404    3.0           232              NaN         NaN  full_bar   
2 -112.046240    3.0            34              NaN         NaN      none   
3 -111.600194    2.5             4              NaN         NaN       NaN   
4 -112.070223    5.0             4              NaN         NaN       NaN   

  Ambience_casual Ambience_classy Ambience_divey Ambience_hipster  \
0           False           False          False            False   
1            True           False          False            False   
2            True           False          False            False   
3           False           False          False            False   
4             NaN             NaN            NaN              NaN   

  Ambience_intimate Ambience_romantic Ambience_touristy Ambience_trendy  \
0             False             False             False           False   
1             False             False             False           False   
2             False             False             False           False   
3             False             False             False           False   
4               NaN               NaN               NaN             NaN   

  Ambience_upscale BestNights_friday BestNights_monday BestNights_saturday  \
0            False               NaN               NaN                 NaN   
1            False               NaN               NaN                 NaN   
2            False               NaN               NaN                 NaN   
3            False               NaN               NaN                 NaN   
4              NaN               NaN               NaN                 NaN   

  BestNights_sunday BestNights_thursday BestNights_tuesday  \
0               NaN                 NaN                NaN   
1               NaN                 NaN                NaN   
2               NaN                 NaN                NaN   
3               NaN                 NaN                NaN   
4               NaN                 NaN                NaN   

  BestNights_wednesday BikeParking BusinessAcceptsBitcoin  \
0                  NaN        True                    NaN   
1                  NaN        True                    NaN   
2                  NaN       False                    NaN   
3                  NaN       False                    NaN   
4                  NaN         NaN                  False   

  BusinessAcceptsCreditCards BusinessParking_garage BusinessParking_lot  \
0                       True                  False                True   
1                       True                  False                True   
2                       True                  False                True   
3                       True                    NaN                 NaN   
4                       True                    NaN                 NaN   

  BusinessParking_street BusinessParking_valet BusinessParking_validated  \
0                  False                 False             

Determing the number of rows and columns of the dataframe

In [5]:
businessDF.shape

(7367, 276)

Checking the data types of the various columns in the dataframe

In [6]:
businessDF.dtypes

business_id                            object
name                                   object
neighborhood                          float64
address                                object
city                                   object
state                                  object
postal_code                           float64
latitude                              float64
longitude                             float64
stars                                 float64
review_count                            int64
AcceptsInsurance                       object
AgesAllowed                            object
Alcohol                                object
Ambience_casual                        object
Ambience_classy                        object
Ambience_divey                         object
Ambience_hipster                       object
Ambience_intimate                      object
Ambience_romantic                      object
Ambience_touristy                      object
Ambience_trendy                   

Taking a back up copy of the dataframe for reference.

In [7]:
businessDF1=businessDF.copy(deep=True)

Cross verifying the columns and the dataframe structure.

In [8]:
businessDF.columns.values

array(['business_id', 'name', 'neighborhood', 'address', 'city', 'state',
       'postal_code', 'latitude', 'longitude', 'stars', 'review_count',
       'AcceptsInsurance', 'AgesAllowed', 'Alcohol', 'Ambience_casual',
       'Ambience_classy', 'Ambience_divey', 'Ambience_hipster',
       'Ambience_intimate', 'Ambience_romantic', 'Ambience_touristy',
       'Ambience_trendy', 'Ambience_upscale', 'BestNights_friday',
       'BestNights_monday', 'BestNights_saturday', 'BestNights_sunday',
       'BestNights_thursday', 'BestNights_tuesday',
       'BestNights_wednesday', 'BikeParking', 'BusinessAcceptsBitcoin',
       'BusinessAcceptsCreditCards', 'BusinessParking_garage',
       'BusinessParking_lot', 'BusinessParking_street',
       'BusinessParking_valet', 'BusinessParking_validated',
       'ByAppointmentOnly', 'BYOB', 'BYOBCorkage', 'Caters', 'CoatCheck',
       'Corkage', 'DietaryRestrictions_dairy-free',
       'DietaryRestrictions_gluten-free', 'DietaryRestrictions_halal',
       '

Determing the overall number of null values for each column of the dataframe

In [9]:
businessDF.isnull().sum(axis=0)

business_id                              0
name                                     0
neighborhood                          7367
address                                 86
city                                     0
state                                    0
postal_code                              9
latitude                                 0
longitude                                0
stars                                    0
review_count                             0
AcceptsInsurance                      7362
AgesAllowed                           7354
Alcohol                               1074
Ambience_casual                        869
Ambience_classy                        869
Ambience_divey                         869
Ambience_hipster                       869
Ambience_intimate                      869
Ambience_romantic                      869
Ambience_touristy                      869
Ambience_trendy                        869
Ambience_upscale                       869
BestNights_

In [10]:
len(businessDF) - businessDF.count()

business_id                              0
name                                     0
neighborhood                          7367
address                                 86
city                                     0
state                                    0
postal_code                              9
latitude                                 0
longitude                                0
stars                                    0
review_count                             0
AcceptsInsurance                      7362
AgesAllowed                           7354
Alcohol                               1074
Ambience_casual                        869
Ambience_classy                        869
Ambience_divey                         869
Ambience_hipster                       869
Ambience_intimate                      869
Ambience_romantic                      869
Ambience_touristy                      869
Ambience_trendy                        869
Ambience_upscale                       869
BestNights_

The below mentioned loop will print the number of NaN values, sub categories and the value counts for all the columns of the dataframe along with the column details. This will help us to group and handle the NaN values of the columns in the dataframe.

In [11]:
for colmn in businessDF.columns.values:
    print('Column name: ',colmn)
    print('No of Unique values: ',businessDF[colmn].nunique())
    print('Unique values: ',businessDF[colmn].unique())
    print('NaN count: ',businessDF[colmn].isnull().sum())
    if(colmn not in ['business_id','name','neighborhood','address','city','state','postal_code','latitude','longitude',
                     'stars','review_count']):
        print('Attribute counts:\n',businessDF[colmn].value_counts(),'\n')
    print('++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++')

Column name:  business_id
No of Unique values:  7367
Unique values:  ['rDMptJYWtnMhpQu_rRXHng' '1WBkAuQg81kokZIPMpn9Zg'
 'iPa__LOhse-hobC2Xmp-Kw' ... '5zva2MTtB5IX6TaoVLL-NA'
 'Gr-2oBg4XyduSKbvnE-i9g' 'UdEmYOnk2iJDY9lpEPAlJQ']
NaN count:  0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  name
No of Unique values:  4172
Unique values:  ["McDonald's" 'Charr An American Burger Bar' 'Little Caesars Pizza' ...
 "Yin's Chinese Resturant" 'Zorbas Grill'
 'Salt & Lime Modern Mexican Grill']
NaN count:  0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  neighborhood
No of Unique values:  0
Unique values:  [nan]
NaN count:  7367
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  address
No of Unique values:  6721
Unique values:  ['719 E Thunderbird Rd' '777 E Thunderbird Rd, Ste 107'
 '1635 E Camelback Rd' ... '1950 W Indian School Rd'
 '9397 E Shea Blvd, Ste 115' '5

Unique values:  ['free' 'paid' nan 'no']
NaN count:  1232
Attribute counts:
 no      3294
free    2797
paid      44
Name: WiFi, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Afghan
No of Unique values:  1
Unique values:  [nan  1.]
NaN count:  7363
Attribute counts:
 1.0    4
Name: category_Afghan, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_African
No of Unique values:  1
Unique values:  [nan  1.]
NaN count:  7357
Attribute counts:
 1.0    10
Name: category_African, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_American (New)
No of Unique values:  1
Unique values:  [nan  1.]
NaN count:  6618
Attribute counts:
 1.0    749
Name: category_American (New), dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_American

Column name:  category_Modern European
No of Unique values:  1
Unique values:  [nan  1.]
NaN count:  7358
Attribute counts:
 1.0    9
Name: category_Modern European, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Mongolian
No of Unique values:  1
Unique values:  [nan  1.]
NaN count:  7357
Attribute counts:
 1.0    10
Name: category_Mongolian, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Moroccan
No of Unique values:  1
Unique values:  [nan  1.]
NaN count:  7363
Attribute counts:
 1.0    4
Name: category_Moroccan, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Music Venues
No of Unique values:  1
Unique values:  [nan  1.]
NaN count:  7323
Attribute counts:
 1.0    44
Name: category_Music Venues, dtype: int64 

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

From the above list we can find that the below mentioned values for the variable 'x' are either not relevant to the restaurant dataframe or have another column having similar details.

In [12]:
for x in ['neighborhood','AcceptsInsurance','BestNights_friday','BestNights_monday','BestNights_saturday',
 'BestNights_sunday','BestNights_thursday','BestNights_tuesday','BestNights_wednesday','BusinessAcceptsBitcoin',
 'ByAppointmentOnly','BYOB','BYOBCorkage','Caters','CoatCheck','Corkage','GoodForDancing','HairSpecializesIn_africanamerican',
 'HairSpecializesIn_asian','HairSpecializesIn_coloring','HairSpecializesIn_curly','HairSpecializesIn_extensions',
 'HairSpecializesIn_kids','HairSpecializesIn_perms','HairSpecializesIn_straightperms','Music_background_music',
 'Music_dj','Music_jukebox','Music_karaoke','Music_live','Music_video','Open24Hours','RestaurantsCounterService','category_Restaurants','hours_Monday',
 'hours_Tuesday','hours_Wednesday','hours_Thursday','hours_Friday','hours_Saturday','hours_Sunday']:
    businessDF.drop(x,axis=1,inplace=True)

Cross verifying the structure and the columns of the dataframe

In [13]:
businessDF.shape

(7367, 235)

NOTE: Other than the below mentioned columns, we are converting all other columns' values to either 0 or 1 if they are having only True or False value and using One hot enocding for all other kinds of values. This is done as it helps us to do the recommendation with ease.

'business_id','name','neighborhood','address','city','state','postal_code','latitude','longitude','stars','review_count'

## Handling missing values

#### AgesAllowed

Replacing missing values in 'AgesAllowed' with 'allages' as it includes '21plus' ages as well. Then converting it to 0's and 1's. Determining the value counts of the same.

In [14]:
businessDF['AgesAllowed']=businessDF['AgesAllowed'].fillna('allages')

In [15]:
businessDF['AgesAllowed'].unique()

array(['allages', '21plus'], dtype=object)

In [16]:
businessDF['AgesAllowed']=businessDF['AgesAllowed'].replace('21plus','1')
businessDF['AgesAllowed']=businessDF['AgesAllowed'].replace('allages','0')

In [17]:
businessDF['AgesAllowed'].value_counts()

0    7356
1      11
Name: AgesAllowed, dtype: int64

#### Alcohol

The 'Alcohol' columns's NaN values are converted to 'none' as they are assumed that the restaurant is not serving any alcohol.Then applying One hot encoding and determing the value counts of the same.

In [18]:
businessDF['Alcohol']=businessDF['Alcohol'].fillna('none')

In [19]:
businessDF['Alcohol'].unique()

array(['none', 'full_bar', 'beer_and_wine'], dtype=object)

In [20]:
businessDF['Alcohol']=businessDF['Alcohol'].replace('none','0')
businessDF['Alcohol']=businessDF['Alcohol'].replace('beer_and_wine','1')
businessDF['Alcohol']=businessDF['Alcohol'].replace('full_bar','2')

In [21]:
businessDF['Alcohol'].value_counts()

0    4560
2    1928
1     879
Name: Alcohol, dtype: int64

#### NoiseLevel

The 'NoiseLevel' having missing values is considered to be 'average' noise.

In [22]:
businessDF['NoiseLevel']=businessDF['NoiseLevel'].fillna('average')

In [23]:
businessDF['NoiseLevel'].unique()

array(['loud', 'average', 'quiet', 'very_loud'], dtype=object)

In [24]:
businessDF['NoiseLevel']=businessDF['NoiseLevel'].replace('quiet','0')
businessDF['NoiseLevel']=businessDF['NoiseLevel'].replace('average','1')
businessDF['NoiseLevel']=businessDF['NoiseLevel'].replace('loud','2')
businessDF['NoiseLevel']=businessDF['NoiseLevel'].replace('very_loud','3')

In [25]:
businessDF['NoiseLevel'].value_counts()

1    5739
0    1133
2     340
3     155
Name: NoiseLevel, dtype: int64

#### RestaurantsAttire

The 'RestaurantsAttire' is assumed to be casual if nothing is specified.

In [26]:
businessDF['RestaurantsAttire']=businessDF['RestaurantsAttire'].fillna('casual')

In [27]:
businessDF['RestaurantsAttire'].unique()

array(['casual', 'dressy', 'formal'], dtype=object)

In [28]:
businessDF['RestaurantsAttire']=businessDF['RestaurantsAttire'].replace('casual','0')
businessDF['RestaurantsAttire']=businessDF['RestaurantsAttire'].replace('dressy','1')
businessDF['RestaurantsAttire']=businessDF['RestaurantsAttire'].replace('formal','2')

In [29]:
businessDF['RestaurantsAttire'].value_counts()

0    7277
1      80
2      10
Name: RestaurantsAttire, dtype: int64

#### RestaurantsPriceRange2

The attribute 'RestaurantsPriceRange2' is used to rank the restaurants based on their prices for the food and drinks. If no price range is present it is considered to be 0.

In [30]:
businessDF['RestaurantsPriceRange2']=businessDF['RestaurantsPriceRange2'].fillna(0)

In [31]:
businessDF['RestaurantsPriceRange2'] = businessDF['RestaurantsPriceRange2'].astype(int)

In [32]:
businessDF['RestaurantsPriceRange2'].dtype

dtype('int32')

In [33]:
businessDF['RestaurantsPriceRange2'].unique()

array([1, 2, 0, 3, 4], dtype=int64)

#### Smoking

The 'Smoking' attribute's missing values is considered to be 'no', as it signifies that the restaurant is not providing either indoor or outdoor smoking area to the customer

In [34]:
businessDF['Smoking']=businessDF['Smoking'].fillna('no')

In [35]:
businessDF['Smoking'].unique()

array(['no', 'outdoor', 'yes'], dtype=object)

In [36]:
businessDF['Smoking']=businessDF['Smoking'].replace('no','0')
businessDF['Smoking']=businessDF['Smoking'].replace('outdoor','1')
businessDF['Smoking']=businessDF['Smoking'].replace('yes','2')

In [37]:
businessDF['Smoking'] = businessDF['Smoking'].astype(int)

In [38]:
businessDF['Smoking'].dtype

dtype('int32')

In [39]:
businessDF['Smoking'].value_counts()

0    6953
1     391
2      23
Name: Smoking, dtype: int64

#### WiFi

'WiFi' column in the dataframe having missing values is treated as a 'no', as it implies that there is not 'WiFi' facility available in the restaurant.

In [40]:
businessDF['WiFi']=businessDF['WiFi'].fillna('no')

In [41]:
businessDF['WiFi'].unique()

array(['free', 'paid', 'no'], dtype=object)

In [42]:
businessDF['WiFi']=businessDF['WiFi'].replace('no','0')
businessDF['WiFi']=businessDF['WiFi'].replace('free','1')
businessDF['WiFi']=businessDF['WiFi'].replace('paid','2')

In [43]:
businessDF['WiFi'].value_counts()

0    4526
1    2797
2      44
Name: WiFi, dtype: int64

#### Music_no_music

The attribute 'Music_no_music' indicates that there is no facility to play music in the restaurant if the value is True. Hence missing values are converted to 'True', followed by converting True to 0 and False to 1 respectively.

In [44]:
businessDF['Music_no_music']=businessDF['Music_no_music'].fillna('True')

In [45]:
businessDF['Music_no_music'].unique()

array(['True', False], dtype=object)

In [46]:
businessDF['Music_no_music']=businessDF['Music_no_music'].replace('True','0')
businessDF['Music_no_music']=businessDF['Music_no_music'].replace(False,'1')

In [47]:
businessDF['Music_no_music'].value_counts()

0    6533
1     834
Name: Music_no_music, dtype: int64

The below mentioned loop is for determining the columns having only either 0 or 1 to handle the missing values together.

In [48]:
list_cat=[]

In [49]:
for colmn in businessDF.columns.values:
    total=businessDF[colmn].nunique()
    if(total == 2 and colmn not in ['AgesAllowed','Alcohol','NoiseLevel','RestaurantsAttire','RestaurantsPriceRange2','Smoking',
 'WiFi']):
        list_cat.append(colmn)

In [50]:
len(list_cat)

42

There are 41 such columns now having only 0 and 1 as their values. Determining the column names below for reference.

In [51]:
for x in list_cat:
    print(x,'\t',type(x))

Ambience_casual 	 <class 'str'>
Ambience_classy 	 <class 'str'>
Ambience_divey 	 <class 'str'>
Ambience_hipster 	 <class 'str'>
Ambience_intimate 	 <class 'str'>
Ambience_romantic 	 <class 'str'>
Ambience_touristy 	 <class 'str'>
Ambience_trendy 	 <class 'str'>
Ambience_upscale 	 <class 'str'>
BikeParking 	 <class 'str'>
BusinessAcceptsCreditCards 	 <class 'str'>
BusinessParking_garage 	 <class 'str'>
BusinessParking_lot 	 <class 'str'>
BusinessParking_street 	 <class 'str'>
BusinessParking_valet 	 <class 'str'>
BusinessParking_validated 	 <class 'str'>
DietaryRestrictions_dairy-free 	 <class 'str'>
DietaryRestrictions_gluten-free 	 <class 'str'>
DietaryRestrictions_halal 	 <class 'str'>
DietaryRestrictions_kosher 	 <class 'str'>
DietaryRestrictions_soy-free 	 <class 'str'>
DietaryRestrictions_vegan 	 <class 'str'>
DietaryRestrictions_vegetarian 	 <class 'str'>
DogsAllowed 	 <class 'str'>
DriveThru 	 <class 'str'>
GoodForKids 	 <class 'str'>
GoodForMeal_breakfast 	 <class 'str'>
GoodFo

Assuming that for all of the above mentioned columns, missing values are indicating that particular feature is not available in the restaurant. Hence marking null values as 'false' and converting the values to 0's and 1's.

In [55]:
for x in list_cat:
    businessDF[x]=businessDF[x].fillna(False)

In [56]:
for x in list_cat:
    businessDF[x]=businessDF[x].replace(True,'1')
    businessDF[x]=businessDF[x].replace(False,'0')

In [57]:
businessDF.head(3)

business_id                          name  \
0  rDMptJYWtnMhpQu_rRXHng                    McDonald's   
1  1WBkAuQg81kokZIPMpn9Zg  Charr An American Burger Bar   
2  iPa__LOhse-hobC2Xmp-Kw                    McDonald's   

                         address     city state  postal_code   latitude  \
0           719 E Thunderbird Rd  Phoenix    AZ      85022.0  33.607070   
1  777 E Thunderbird Rd, Ste 107  Phoenix    AZ      85022.0  33.607310   
2            1635 E Camelback Rd  Phoenix    AZ      85016.0  33.508765   

    longitude  stars  review_count AgesAllowed Alcohol Ambience_casual  \
0 -112.064382    1.0            10           0       0               0   
1 -112.063404    3.0           232           0       2               1   
2 -112.046240    3.0            34           0       0               1   

  Ambience_classy Ambience_divey Ambience_hipster Ambience_intimate  \
0               0              0                0                 0   
1               0              0                0                 0   
2               0              0                0                 0   

  Ambience_romantic Ambience_touristy Ambience_trendy Ambience_upscale  \
0                 0                 0               0                0   
1                 0                 0               0                0   
2                 0                 0               0                0   

  BikeParking BusinessAcceptsCreditCards BusinessParking_garage  \
0           1                          1                      0   
1           1                          1                      0   
2           0                          1                      0   

  BusinessParking_lot BusinessParking_street BusinessParking_valet  \
0                   1                      0                     0   
1                   1                      0                     0   
2                   1                      0                     0   

  BusinessParking_validated DietaryRestrictions_dairy-free  \
0                         0                              0   
1                         0                              0   
2                         0                              0   

  DietaryRestrictions_gluten-free DietaryRestrictions_halal  \
0                               0                         0   
1                               0                         0   
2                               0                         0   

  DietaryRestrictions_kosher DietaryRestrictions_soy-free  \
0                          0                            0   
1                          0                            0   
2                          0                            0   

  DietaryRestrictions_vegan DietaryRestrictions_vegetarian DogsAllowed  \
0                         0                              0           0   
1                         0                              0           0   
2                         0                              0           0   

  DriveThru GoodForKids GoodForMeal_breakfast GoodForMeal_brunch  \
0         1           1                     1                  0   
1         0           1                     0                  0   
2         1           1                     1                  0   

  GoodForMeal_dessert GoodForMeal_dinner GoodForMeal_latenight  \
0                   0                  0                     0   
1                   0                  1                     0   
2                   0                  1                     1   

  GoodForMeal_lunch HappyHour HasTV Music_no_music NoiseLevel OutdoorSeating  \
0                 1         0     1              0          2              0   
1                 0         0     1              0          1              1   
2                 1         0     0              0          2              0   

  RestaurantsAttire RestaurantsDelivery RestaurantsGoodForGroups  \
0                 0                   0                        1   
1       

#### Cuisine Category

All of the below mentioned category columns are converted to 0's and 1's, after handing their missing values as 0's and converting their datatype to integer.

In [58]:
category_cols = ['category_Afghan','category_African', 'category_American (New)','category_American (Traditional)',
'category_Arabian','category_Arcades', 'category_Argentine', 'category_Armenian',
'category_Arts & Entertainment', 'category_Asian Fusion','category_Australian', 'category_Austrian', 'category_Bagels',
'category_Bakeries', 'category_Barbeque', 'category_Bars','category_Beer Bar', 'category_Beer Gardens', 'category_Beer',
'category_Belgian', 'category_Bistros', 'category_Brasseries',
'category_Brazilian', 'category_Breakfast & Brunch','category_Breweries', 'category_Brewpubs', 'category_British',
'category_Bubble Tea', 'category_Buffets', 'category_Burgers','category_Cafes', 'category_Cafeteria', 'category_Cajun/Creole',
'category_Cambodian', 'category_Cantonese', 'category_Caribbean',
'category_Casinos', 'category_Caterers', 'category_Cheesesteaks',
'category_Chicken Shop', 'category_Chicken Wings','category_Chinese', 'category_Chocolatiers & Shops',
'category_Cocktail Bars', 'category_Coffee & Tea Supplies','category_Coffee & Tea', 'category_Coffee Roasteries',
'category_Coffeeshops', 'category_Colombian','category_Comfort Food', 'category_Creperies', 'category_Cuban',
'category_Cupcakes', 'category_Custom Cakes', 'category_Czech',
'category_Delis', 'category_Desserts', 'category_Dim Sum',
'category_Diners', 'category_Dinner Theater','category_Do-It-Yourself Food', 'category_Dominican',
'category_Donuts', 'category_Eatertainment', 'category_Ethiopian','category_Ethnic Food', 'category_Event Planning & Services',
'category_Falafel', 'category_Fast Food', 'category_Festivals',
'category_Filipino', 'category_Fish & Chips', 'category_Fondue',
'category_Food Court', 'category_Food Delivery Services',
'category_Food Stands', 'category_Food Trucks', 'category_Food',
'category_French', 'category_Gastropubs', 'category_German',
'category_Gluten-Free', 'category_Greek', 'category_Grocery',
'category_Halal', 'category_Hawaiian', 'category_Herbs & Spices',
'category_Hookah Bars', 'category_Hot Dogs', 'category_Hot Pot',
'category_Hotel bar', 'category_Hotels',
'category_Ice Cream & Frozen Yogurt', 'category_Imported Food',
'category_Indian', 'category_Indonesian', 'category_Irish Pub',
'category_Irish', 'category_Italian', 'category_Izakaya',
'category_Japanese', 'category_Juice Bars & Smoothies',
'category_Kebab', 'category_Korean', 'category_Kosher',
'category_Laotian', 'category_Latin American', 'category_Lebanese',
'category_Live/Raw Food', 'category_Local Flavor',
'category_Lounges', 'category_Macarons', 'category_Malaysian',
'category_Marinas', 'category_Meat Shops', 'category_Mediterranean',
'category_Mexican', 'category_Middle Eastern',
'category_Modern European', 'category_Mongolian',
'category_Moroccan', 'category_Music Venues',
'category_New Mexican Cuisine', 'category_Nightlife',
'category_Noodles', 'category_Pakistani', 'category_Pan Asian',
'category_Pasta Shops', 'category_Patisserie/Cake Shop',
'category_Persian/Iranian', 'category_Peruvian', 'category_Pizza',
'category_Polish', 'category_Popcorn Shops', 'category_Poutineries',
'category_Pretzels', 'category_Pubs', 'category_Puerto Rican',
'category_Ramen', 'category_Russian','category_Salad', 'category_Salvadoran', 'category_Sandwiches',
'category_Scandinavian', 'category_Seafood', 'category_Soul Food',
'category_Soup', 'category_Southern', 'category_Spanish',
'category_Specialty Food', 'category_Sports Bars',
'category_Steakhouses', 'category_Street Vendors',
'category_Supper Clubs', 'category_Sushi Bars', 'category_Szechuan',
'category_Tacos', 'category_Taiwanese', 'category_Tapas Bars',
'category_Tapas/Small Plates', 'category_Tea Rooms',
'category_Teppanyaki', 'category_Tex-Mex', 'category_Thai',
'category_Themed Cafes', 'category_Trinidadian', 'category_Turkish',
'category_Ukrainian', 'category_Uzbek', 'category_Vegan',
'category_Vegetarian', 'category_Vietnamese', 'category_Waffles',
'category_Wine & Spirits', 'category_Wine Bars', 'category_Wraps']

In [59]:
businessDF[category_cols].head(5)

category_Afghan  category_African  category_American (New)  \
0              NaN               NaN                      NaN   
1              NaN               NaN                      NaN   
2              NaN               NaN                      NaN   
3              NaN               NaN                      NaN   
4              NaN               NaN                      NaN   

   category_American (Traditional)  category_Arabian  category_Arcades  \
0                              NaN               NaN               NaN   
1                              NaN               NaN               NaN   
2                              NaN               NaN               NaN   
3                              NaN               NaN               NaN   
4                              NaN               NaN               NaN   

   category_Argentine  category_Armenian  category_Arts & Entertainment  \
0                 NaN                NaN                            NaN   
1                 NaN                NaN                            NaN   
2                 NaN                NaN                            NaN   
3                 NaN                NaN                            NaN   
4                 NaN                NaN                            NaN   

   category_Asian Fusion  category_Australian  category_Austrian  \
0                    NaN                  NaN                NaN   
1                    NaN                  NaN                NaN   
2                    NaN                  NaN                NaN   
3                    NaN                  NaN                NaN   
4                    NaN                  NaN                NaN   

   category_Bagels  category_Bakeries  category_Barbeque  category_Bars  \
0              NaN                NaN                NaN            NaN   
1              NaN                NaN                NaN            NaN   
2              NaN                NaN                NaN            NaN   
3              NaN                NaN                NaN            NaN   
4              NaN                NaN                NaN            NaN   

   category_Beer Bar  category_Beer Gardens  category_Beer  category_Belgian  \
0                NaN                    NaN            NaN               NaN   
1                NaN                    NaN            NaN               NaN   
2                NaN                    NaN            NaN               NaN   
3                NaN                    NaN            NaN               NaN   
4                NaN                    NaN            NaN               NaN   

   category_Bistros  category_Brasseries  category_Brazilian  \
0               NaN                  NaN                 NaN   
1               NaN                  NaN                 NaN   
2               NaN                  NaN                 NaN   
3               NaN                  NaN                 NaN   
4               NaN                  NaN                 NaN   

   category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
0                          NaN                 NaN                NaN   
1                          NaN                 NaN                NaN   
2                          NaN                 NaN                NaN   
3                          NaN                 NaN                NaN   
4                          NaN                 NaN                NaN   

   category_British  category_Bubble Tea  category_Buffets  category_Burgers  \
0               NaN                  NaN               NaN               1.0   
1               NaN                  NaN               NaN               1.0   
2               NaN                  NaN               NaN               1.0   
3               NaN                  NaN               NaN               NaN   
4               NaN                  NaN               NaN               NaN   

   category_Cafes  category_Cafeteria  category_Cajun/Creole  \
0     

In [60]:
len(category_cols)

176

There is a total of 176 category columns in our restaurant business dataframe.

In [61]:
for x in category_cols:
    businessDF[x]=businessDF[x].fillna(0.0)

In [62]:
businessDF[category_cols].head(5)

category_Afghan  category_African  category_American (New)  \
0              0.0               0.0                      0.0   
1              0.0               0.0                      0.0   
2              0.0               0.0                      0.0   
3              0.0               0.0                      0.0   
4              0.0               0.0                      0.0   

   category_American (Traditional)  category_Arabian  category_Arcades  \
0                              0.0               0.0               0.0   
1                              0.0               0.0               0.0   
2                              0.0               0.0               0.0   
3                              0.0               0.0               0.0   
4                              0.0               0.0               0.0   

   category_Argentine  category_Armenian  category_Arts & Entertainment  \
0                 0.0                0.0                            0.0   
1                 0.0                0.0                            0.0   
2                 0.0                0.0                            0.0   
3                 0.0                0.0                            0.0   
4                 0.0                0.0                            0.0   

   category_Asian Fusion  category_Australian  category_Austrian  \
0                    0.0                  0.0                0.0   
1                    0.0                  0.0                0.0   
2                    0.0                  0.0                0.0   
3                    0.0                  0.0                0.0   
4                    0.0                  0.0                0.0   

   category_Bagels  category_Bakeries  category_Barbeque  category_Bars  \
0              0.0                0.0                0.0            0.0   
1              0.0                0.0                0.0            0.0   
2              0.0                0.0                0.0            0.0   
3              0.0                0.0                0.0            0.0   
4              0.0                0.0                0.0            0.0   

   category_Beer Bar  category_Beer Gardens  category_Beer  category_Belgian  \
0                0.0                    0.0            0.0               0.0   
1                0.0                    0.0            0.0               0.0   
2                0.0                    0.0            0.0               0.0   
3                0.0                    0.0            0.0               0.0   
4                0.0                    0.0            0.0               0.0   

   category_Bistros  category_Brasseries  category_Brazilian  \
0               0.0                  0.0                 0.0   
1               0.0                  0.0                 0.0   
2               0.0                  0.0                 0.0   
3               0.0                  0.0                 0.0   
4               0.0                  0.0                 0.0   

   category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
0                          0.0                 0.0                0.0   
1                          0.0                 0.0                0.0   
2                          0.0                 0.0                0.0   
3                          0.0                 0.0                0.0   
4                          0.0                 0.0                0.0   

   category_British  category_Bubble Tea  category_Buffets  category_Burgers  \
0               0.0                  0.0               0.0               1.0   
1               0.0                  0.0               0.0               1.0   
2               0.0                  0.0               0.0               1.0   
3               0.0                  0.0               0.0               0.0   
4               0.0                  0.0               0.0               0.0   

   category_Cafes  category_Cafeteria  category_Cajun/Creole  \
0     

In [63]:
import string

In [64]:
for x in category_cols:
    businessDF[x]=businessDF[x].astype(int)

In [65]:
businessDF[category_cols].head(4)

category_Afghan  category_African  category_American (New)  \
0                0                 0                        0   
1                0                 0                        0   
2                0                 0                        0   
3                0                 0                        0   

   category_American (Traditional)  category_Arabian  category_Arcades  \
0                                0                 0                 0   
1                                0                 0                 0   
2                                0                 0                 0   
3                                0                 0                 0   

   category_Argentine  category_Armenian  category_Arts & Entertainment  \
0                   0                  0                              0   
1                   0                  0                              0   
2                   0                  0                              0   
3                   0                  0                              0   

   category_Asian Fusion  category_Australian  category_Austrian  \
0                      0                    0                  0   
1                      0                    0                  0   
2                      0                    0                  0   
3                      0                    0                  0   

   category_Bagels  category_Bakeries  category_Barbeque  category_Bars  \
0                0                  0                  0              0   
1                0                  0                  0              0   
2                0                  0                  0              0   
3                0                  0                  0              0   

   category_Beer Bar  category_Beer Gardens  category_Beer  category_Belgian  \
0                  0                      0              0                 0   
1                  0                      0              0                 0   
2                  0                      0              0                 0   
3                  0                      0              0                 0   

   category_Bistros  category_Brasseries  category_Brazilian  \
0                 0                    0                   0   
1                 0                    0                   0   
2                 0                    0                   0   
3                 0                    0                   0   

   category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
0                            0                   0                  0   
1                            0                   0                  0   
2                            0                   0                  0   
3                            0                   0                  0   

   category_British  category_Bubble Tea  category_Buffets  category_Burgers  \
0                 0                    0                 0                 1   
1                 0                    0                 0                 1   
2                 0                    0                 0                 1   
3                 0                    0                 0                 0   

   category_Cafes  category_Cafeteria  category_Cajun/Creole  \
0               0                   0                      0   
1               0                   0                      0   
2               0                   0                      0   
3               0                   0                      0   

   category_Cambodian  category_Cantonese  category_Caribbean  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   

   category_Casinos  category_Caterers  category_Cheesesteaks  \
0           

Re-running the first loop, to determine if any columns' missing values were not handled.

In [66]:
list_nan=[]

In [67]:
for colmn in businessDF.columns.values:
    print('Column name: ',colmn)
    print('No of Unique values: ',businessDF[colmn].nunique())
    print('Unique values: ',businessDF[colmn].unique())
    print('NaN count: ',businessDF[colmn].isnull().sum())
    if(colmn not in ['business_id','name','neighborhood','address','city','state','postal_code','latitude','longitude','stars',
                     'review_count']):
        print('Attribute counts:\n',businessDF[colmn].value_counts(),'\n')
        print('++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    else:
        print('++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++')
    total_nan=businessDF[colmn].isnull().sum()
    if(total_nan > 0):
        list_nan.append(colmn)

Column name:  business_id
No of Unique values:  7367
Unique values:  ['rDMptJYWtnMhpQu_rRXHng' '1WBkAuQg81kokZIPMpn9Zg'
 'iPa__LOhse-hobC2Xmp-Kw' ... '5zva2MTtB5IX6TaoVLL-NA'
 'Gr-2oBg4XyduSKbvnE-i9g' 'UdEmYOnk2iJDY9lpEPAlJQ']
NaN count:  0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  name
No of Unique values:  4172
Unique values:  ["McDonald's" 'Charr An American Burger Bar' 'Little Caesars Pizza' ...
 "Yin's Chinese Resturant" 'Zorbas Grill'
 'Salt & Lime Modern Mexican Grill']
NaN count:  0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  address
No of Unique values:  6721
Unique values:  ['719 E Thunderbird Rd' '777 E Thunderbird Rd, Ste 107'
 '1635 E Camelback Rd' ... '1950 W Indian School Rd'
 '9397 E Shea Blvd, Ste 115' '590 N Alma School Rd, Ste 35']
NaN count:  86
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  city
No of Unique values:  41
U

Column name:  BikeParking
No of Unique values:  2
Unique values:  ['1' '0']
NaN count:  0
Attribute counts:
 1    5444
0    1923
Name: BikeParking, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  BusinessAcceptsCreditCards
No of Unique values:  2
Unique values:  ['1' '0']
NaN count:  0
Attribute counts:
 1    7097
0     270
Name: BusinessAcceptsCreditCards, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  BusinessParking_garage
No of Unique values:  2
Unique values:  ['0' '1']
NaN count:  0
Attribute counts:
 0    7139
1     228
Name: BusinessParking_garage, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  BusinessParking_lot
No of Unique values:  2
Unique values:  ['1' '0']
NaN count:  0
Attribute counts:
 1    3777
0    3590
Name: BusinessParking_lot, dtype: int64 

+++++++++++++++++++++++++++++++++++++++++++

Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7349
1      18
Name: category_Coffee Roasteries, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Coffeeshops
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7366
1       1
Name: category_Coffeeshops, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Colombian
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7364
1       3
Name: category_Colombian, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Comfort Food
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7320
1      47
Name: category_Comfort Food, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Creperie

Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7360
1       7
Name: category_Spanish, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Specialty Food
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7206
1     161
Name: category_Specialty Food, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Sports Bars
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7089
1     278
Name: category_Sports Bars, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Steakhouses
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7188
1     179
Name: category_Steakhouses, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Street Ven

In [68]:
len(list_nan)

2

In [69]:
list_nan

['address', 'postal_code']

We can see that, 2 columns namely 'address' and 'postal_code' are not having their missing values handled. Also, since we are just recommending the restaurants to the user we are not going to handle 'address' columns' missing values. 
The 'postal_code' columns' values are being handled after plotting the map in Tableau for EDA.

#### postal code

In [70]:
businessDF[businessDF['postal_code'].isnull()]

business_id                                         name  \
1262  8N5A5jW8sTG7ozGmZ_uj0Q           Paradise Valley Burger Chase Field   
1520  o-cqIwS2nWJGWA6nNPQ2_w                             Hot Cookie Truck   
1614  3LWTG3f52gdVZILl42FCAg                                 Vogue Bistro   
1760  DscqZ5DUZSWTggbv6N_j3Q  Taquizas "Yiyo" Catering and Party Supplies   
4125  BxRsg5YTYnxXEhoGcabydg                             Wandering Donkey   
4217  R0gfUYIiC5MlLxGjRcYifw                    Zita Mediterranean Eatery   
4623  YH9jx2vlDBD47qTBoCvkoA                             Leafy Sea Dragon   
5426  wFJFBZDMcV0hBMYOx88IYQ                                    Satay Hut   
6768  tY_Hmm0rT4sRDL-geEYQmg                                  Time Square   

                                address        city state  postal_code  \
1262  Main Concourse Behind The Catcher     Phoenix    AZ          NaN   
1520                                NaN        Mesa    AZ          NaN   
1614                                NaN    Surprise    AZ          NaN   
1760                                NaN     Phoenix    AZ          NaN   
4125                                NaN  Cave Creek    AZ          NaN   
4217          Superstition Springs Blvd        Mesa    AZ          NaN   
4623                                NaN     Phoenix    AZ          NaN   
5426                                NaN     Phoenix    AZ          NaN   
6768                    I 17 Deervalley     Phoenix    AZ          NaN   

       latitude   longitude  stars  review_count AgesAllowed Alcohol  \
1262  33.445109 -112.066824    4.0            10           0       0   
1520  33.415184 -111.831472    4.0             9           0       0   
1614  33.639099 -112.395760    3.5             8           0       0   
1760  33.448377 -112.074037    4.0             5           0       0   
4125  33.833372 -111.950704    2.5            14           0       0   
4217  33.383932 -111.684941    2.5             7           0       0   
4623  33.448377 -112.074037    5.0             3           0       0   
5426  33.448377 -112.074037    3.5            27           0       0   
6768  33.685141 -112.116859    4.5            22           0       2   

     Ambience_casual Ambience_classy Ambience_divey Ambience_hipster  \
1262               0               0              0                0   
1520               0               0              0                0   
1614               0               0              0                0   
1760               0               0              0                0   
4125               0               0              0                0   
4217               0               0              0                0   
4623               0               0              0                0   
5426               1               0              0                0   
6768               1               0              0                0   

     Ambience_intimate Ambience_romantic Ambience_touristy Ambience_trendy  \
1262                 0                 0                 0               0   
1520                 0                 0                 0               0   
1614                 0                 0                 0               0   
1760                 0                 0                 0               0   
4125                 0                 0                 0               0   
4217                 0                 0                 0               0   
4623                 0                 0                 0               0   
5426                 0                 0                 0               0   
6768                 0                 0                 0               0   

     Ambience_upscale BikeParking BusinessAcceptsCreditCards  \
1262                0           1                          1   
1520                0           0                          1   
1614                0           0                          0   
1760                0     

In [71]:
businessDF['postal_code'].isnull().sum()

9

There is a total of 9 businesses' that are not having zip code values. These values are determined from Tableau afer plotting the map and taking the closest value to the missing zip code value or determing the actual zip code value.
They are present in the zipFill vector below. From the above python statement we are determing the bussiness names for handling their missing zip codes as shown below.

In [72]:
zipFill=[85004.0,85210.0,85374.0,85003.0,85331.0,85206.0,85003.0,85003.0,85027.0]

j=0
for x in ['Paradise Valley Burger Chase Field','Hot Cookie Truck','Vogue Bistro','Taquizas "Yiyo" Catering and Party Supplies',
          'Wandering Donkey','Zita Mediterranean Eatery','Leafy Sea Dragon','Satay Hut','Time Square']:
    businessDF.iloc[businessDF[businessDF['name']==x]['postal_code'].index[0],5]= zipFill[j]
    j=j+1                               

In [73]:
businessDF.iloc[businessDF[businessDF['business_id']=='8N5A5jW8sTG7ozGmZ_uj0Q']['postal_code'].index[0],5] = 85004.0

Verifying the above zip code changes for a particular business above.

In [74]:
businessDF[businessDF['business_id']=='8N5A5jW8sTG7ozGmZ_uj0Q']

business_id                                name  \
1262  8N5A5jW8sTG7ozGmZ_uj0Q  Paradise Valley Burger Chase Field   

                                address     city state  postal_code  \
1262  Main Concourse Behind The Catcher  Phoenix    AZ      85004.0   

       latitude   longitude  stars  review_count AgesAllowed Alcohol  \
1262  33.445109 -112.066824    4.0            10           0       0   

     Ambience_casual Ambience_classy Ambience_divey Ambience_hipster  \
1262               0               0              0                0   

     Ambience_intimate Ambience_romantic Ambience_touristy Ambience_trendy  \
1262                 0                 0                 0               0   

     Ambience_upscale BikeParking BusinessAcceptsCreditCards  \
1262                0           1                          1   

     BusinessParking_garage BusinessParking_lot BusinessParking_street  \
1262                      0                   0                      0   

     BusinessParking_valet BusinessParking_validated  \
1262                     0                         0   

     DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
1262                              0                               0   

     DietaryRestrictions_halal DietaryRestrictions_kosher  \
1262                         0                          0   

     DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
1262                            0                         0   

     DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
1262                              0           0         0           1   

     GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
1262                     0                  0                   0   

     GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
1262                  0                     0                 0         0   

     HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
1262     1              0          1              1                 0   

     RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
1262                   0                        1                       1   

     RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
1262                       0                       0                  1   

      Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
1262        0                    0    0                0                 0   

      category_American (New)  category_American (Traditional)  \
1262                        0                                1   

      category_Arabian  category_Arcades  category_Argentine  \
1262                 0                 0                   0   

      category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
1262                  0                              0                      0   

      category_Australian  category_Austrian  category_Bagels  \
1262                    0                  0                0   

      category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
1262                  0                  0              0                  0   

      category_Beer Gardens  category_Beer  category_Belgian  \
1262                      0              0                 0   

      category_Bistros  category_Brasseries  category_Brazilian  \
1262                 0                    0                   0   

      category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
1262                            0                   0                  0   

      category_British  category_Bubble Tea  category_Buffets  \
1262                 0                    0                 0   

      category_Burgers  category_Cafes  category_Cafeteria  \
1262                 1               0                   0   

      category_Cajun/Creole  category_Cambodian  category_Cantone

In [75]:
businessDF[businessDF['postal_code'].isnull()]['business_id']

Series([], Name: business_id, dtype: object)

In [76]:
businessDF.iloc[businessDF[businessDF['business_id']=='o-cqIwS2nWJGWA6nNPQ2_w']['postal_code'].index[0],5] = 85210
businessDF.iloc[businessDF[businessDF['business_id']=='3LWTG3f52gdVZILl42FCAg']['postal_code'].index[0],5] = 85374
businessDF.iloc[businessDF[businessDF['business_id']=='DscqZ5DUZSWTggbv6N_j3Q']['postal_code'].index[0],5] = 85003
businessDF.iloc[businessDF[businessDF['business_id']=='BxRsg5YTYnxXEhoGcabydg']['postal_code'].index[0],5] = 85331
businessDF.iloc[businessDF[businessDF['business_id']=='R0gfUYIiC5MlLxGjRcYifw']['postal_code'].index[0],5] = 85206
businessDF.iloc[businessDF[businessDF['business_id']=='YH9jx2vlDBD47qTBoCvkoA']['postal_code'].index[0],5] = 85003
businessDF.iloc[businessDF[businessDF['business_id']=='wFJFBZDMcV0hBMYOx88IYQ']['postal_code'].index[0],5] = 85003
businessDF.iloc[businessDF[businessDF['business_id']=='tY_Hmm0rT4sRDL-geEYQmg']['postal_code'].index[0],5] = 85027

In [77]:
businessDF[businessDF['postal_code'].isnull()]['name'].count()

0

Converting 'postal_code' column values of type int, as now it contains no missing values.

In [78]:
businessDF['postal_code'] = businessDF['postal_code'].astype(int)

In [79]:
businessDF['postal_code'].dtype

dtype('int32')

#### Other  data cleansing

The below mentioned handling of business dataframe's values is due to discrepancies found in Tableau during plotting of charts, maps and graphs.
We were able to find restaurants with same name but with extra symbols, wrong city details based on the postal code provided in the data and also the business having wrong latitude and longitude values.
Such discrepancies are handled below.

In [80]:
businessDF[businessDF['name']=='Little Caesars Pizza'].head(5)

business_id                  name                    address  \
3    kKx8iCJkomVQBdWHnmmOiA  Little Caesars Pizza       10720 E Southern Ave   
28   D1E_6MBFKeU2a7EQ4IwoEQ  Little Caesars Pizza      13011 W Greenway Blvd   
34   VqF6Uky7SGfjWitgxrhlJA  Little Caesars Pizza           6466 S Higley Rd   
97   Lvr6DdVkFI8IMGfRvUcXQA  Little Caesars Pizza  4340 W McDowell Rd, Ste 6   
242  xrpZFPRMf5WVgVXT5uuJ6Q  Little Caesars Pizza           911 S Lindsay Rd   

          city state  postal_code   latitude   longitude  stars  review_count  \
3         Mesa    AZ        85209  33.394877 -111.600194    2.5             4   
28   El Mirage    AZ        85335  33.623055 -112.339758    2.5            15   
34     Gilbert    AZ        85298  33.231942 -111.721218    4.0             9   
97     Phoenix    AZ        85035  33.466332 -112.153483    1.0             3   
242    Gilbert    AZ        85296  33.333727 -111.771796    3.0             8   

    AgesAllowed Alcohol Ambience_casual Ambience_classy Ambience_divey  \
3             0       0               0               0              0   
28            0       0               0               0              0   
34            0       0               0               0              0   
97            0       0               0               0              0   
242           0       0               0               0              0   

    Ambience_hipster Ambience_intimate Ambience_romantic Ambience_touristy  \
3                  0                 0                 0                 0   
28                 0                 0                 0                 0   
34                 0                 0                 0                 0   
97                 0                 0                 0                 0   
242                0                 0                 0                 0   

    Ambience_trendy Ambience_upscale BikeParking BusinessAcceptsCreditCards  \
3                 0                0           0                          1   
28                0                0           0                          1   
34                0                0           0                          1   
97                0                0           0                          1   
242               0                0           0                          0   

    BusinessParking_garage BusinessParking_lot BusinessParking_street  \
3                        0                   0                      0   
28                       0                   0                      0   
34                       0                   0                      0   
97                       0                   0                      0   
242                      0                   0                      0   

    BusinessParking_valet BusinessParking_validated  \
3                       0                         0   
28                      0                         0   
34                      0                         0   
97                      0                         0   
242                     0                         0   

    DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
3                                0                               0   
28                               0                               0   
34                               0                               0   
97                               0                               0   
242                              0                               0   

    DietaryRestrictions_halal DietaryRestrictions_kosher  \
3                           0                          0   
28                          0                          0   
34                          0                          0   
97                          0                          0   
242                         0                          0   

    DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
3                              0             

In [81]:
businessDF.loc[businessDF['business_id']=='ivYI5FZ7ULlfaqsc-wIVSQ']

business_id     name                           address  \
619  ivYI5FZ7ULlfaqsc-wIVSQ  Wendy's  Sky Harbor International Airport   

             city state  postal_code   latitude   longitude  stars  \
619  Central City    AZ        85034  33.439648 -112.026154    3.0   

     review_count AgesAllowed Alcohol Ambience_casual Ambience_classy  \
619             9           0       0               0               0   

    Ambience_divey Ambience_hipster Ambience_intimate Ambience_romantic  \
619              0                0                 0                 0   

    Ambience_touristy Ambience_trendy Ambience_upscale BikeParking  \
619                 0               0                0           0   

    BusinessAcceptsCreditCards BusinessParking_garage BusinessParking_lot  \
619                          1                      0                   0   

    BusinessParking_street BusinessParking_valet BusinessParking_validated  \
619                      0                     0                         0   

    DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
619                              0                               0   

    DietaryRestrictions_halal DietaryRestrictions_kosher  \
619                         0                          0   

    DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
619                            0                         0   

    DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
619                              0           0         0           1   

    GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
619                     0                  0                   0   

    GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
619                  0                     0                 0         0   

    HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
619     0              0          1              0                 0   

    RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
619                   0                        1                       1   

    RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
619                       0                       0                  1   

     Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
619        0                    0    0                0                 0   

     category_American (New)  category_American (Traditional)  \
619                        0                                0   

     category_Arabian  category_Arcades  category_Argentine  \
619                 0                 0                   0   

     category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
619                  0                              0                      0   

     category_Australian  category_Austrian  category_Bagels  \
619                    0                  0                0   

     category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
619                  0                  0              0                  0   

     category_Beer Gardens  category_Beer  category_Belgian  category_Bistros  \
619                      0              0                 0                 0   

     category_Brasseries  category_Brazilian  category_Breakfast & Brunch  \
619                    0                   0                            1   

     category_Breweries  category_Brewpubs  category_British  \
619                   0                  0                 0   

     category_Bubble Tea  category_Buffets  category_Burgers  category_Cafes  \
619                    0                 0                 1               0   

     category_Cafeteria  category_Cajun/Creole  category_Cambodian  \
619                   0                      0                   0   

     category_Cantonese  category_Caribbean  category_Casinos  \
619                   0       

In [82]:
businessDF[businessDF['business_id']=='ivYI5FZ7ULlfaqsc-wIVSQ']

business_id     name                           address  \
619  ivYI5FZ7ULlfaqsc-wIVSQ  Wendy's  Sky Harbor International Airport   

             city state  postal_code   latitude   longitude  stars  \
619  Central City    AZ        85034  33.439648 -112.026154    3.0   

     review_count AgesAllowed Alcohol Ambience_casual Ambience_classy  \
619             9           0       0               0               0   

    Ambience_divey Ambience_hipster Ambience_intimate Ambience_romantic  \
619              0                0                 0                 0   

    Ambience_touristy Ambience_trendy Ambience_upscale BikeParking  \
619                 0               0                0           0   

    BusinessAcceptsCreditCards BusinessParking_garage BusinessParking_lot  \
619                          1                      0                   0   

    BusinessParking_street BusinessParking_valet BusinessParking_validated  \
619                      0                     0                         0   

    DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
619                              0                               0   

    DietaryRestrictions_halal DietaryRestrictions_kosher  \
619                         0                          0   

    DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
619                            0                         0   

    DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
619                              0           0         0           1   

    GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
619                     0                  0                   0   

    GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
619                  0                     0                 0         0   

    HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
619     0              0          1              0                 0   

    RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
619                   0                        1                       1   

    RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
619                       0                       0                  1   

     Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
619        0                    0    0                0                 0   

     category_American (New)  category_American (Traditional)  \
619                        0                                0   

     category_Arabian  category_Arcades  category_Argentine  \
619                 0                 0                   0   

     category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
619                  0                              0                      0   

     category_Australian  category_Austrian  category_Bagels  \
619                    0                  0                0   

     category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
619                  0                  0              0                  0   

     category_Beer Gardens  category_Beer  category_Belgian  category_Bistros  \
619                      0              0                 0                 0   

     category_Brasseries  category_Brazilian  category_Breakfast & Brunch  \
619                    0                   0                            1   

     category_Breweries  category_Brewpubs  category_British  \
619                   0                  0                 0   

     category_Bubble Tea  category_Buffets  category_Burgers  category_Cafes  \
619                    0                 0                 1               0   

     category_Cafeteria  category_Cajun/Creole  category_Cambodian  \
619                   0                      0                   0   

     category_Cantonese  category_Caribbean  category_Casinos  \
619                   0       

In [83]:
businessDF.iloc[619,3]='Phoenix'

In [84]:
businessDF[businessDF['business_id']=='ivYI5FZ7ULlfaqsc-wIVSQ']['city']

619    Phoenix
Name: city, dtype: object

In [85]:
businessDF.iloc[businessDF[businessDF['business_id']=='j8j0IV_eemJpFuRRvdNobQ']['city'].index[0],3] = 'Phoenix'

In [86]:
businessDF[businessDF['business_id']=='j8j0IV_eemJpFuRRvdNobQ']

business_id                  name             address  \
1930  j8j0IV_eemJpFuRRvdNobQ  Cheuvront Restaurant  Sky Harbor Airport   

         city state  postal_code   latitude   longitude  stars  review_count  \
1930  Phoenix    AZ        85034  33.434194 -111.999245    3.0            13   

     AgesAllowed Alcohol Ambience_casual Ambience_classy Ambience_divey  \
1930           0       2               0               0              0   

     Ambience_hipster Ambience_intimate Ambience_romantic Ambience_touristy  \
1930                0                 0                 0                 0   

     Ambience_trendy Ambience_upscale BikeParking BusinessAcceptsCreditCards  \
1930               0                0           0                          1   

     BusinessParking_garage BusinessParking_lot BusinessParking_street  \
1930                      0                   0                      0   

     BusinessParking_valet BusinessParking_validated  \
1930                     0                         0   

     DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
1930                              0                               0   

     DietaryRestrictions_halal DietaryRestrictions_kosher  \
1930                         0                          0   

     DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
1930                            0                         0   

     DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
1930                              0           0         0           0   

     GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
1930                     0                  0                   0   

     GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
1930                  0                     0                 0         0   

     HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
1930     0              0          0              0                 0   

     RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
1930                   0                        0                       2   

     RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
1930                       0                       1                  1   

      Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
1930        0                    0    0                0                 0   

      category_American (New)  category_American (Traditional)  \
1930                        0                                0   

      category_Arabian  category_Arcades  category_Argentine  \
1930                 0                 0                   0   

      category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
1930                  0                              0                      0   

      category_Australian  category_Austrian  category_Bagels  \
1930                    0                  0                0   

      category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
1930                  0                  0              0                  0   

      category_Beer Gardens  category_Beer  category_Belgian  \
1930                      0              0                 0   

      category_Bistros  category_Brasseries  category_Brazilian  \
1930                 0                    0                   0   

      category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
1930                            0                   0                  0   

      category_British  category_Bubble Tea  category_Buffets  \
1930                 0                    0                 0   

      category_Burgers  category_Cafes  category_Cafeteria  \
1930                 0               1                   0   

      category_Cajun/Creole  category_Cambodian  category_Cantonese  \
1930                      0                   0                   0  

In [87]:
businessDF.iloc[businessDF[businessDF['business_id']=='Rut5I04WZ2Hm2GEyDwk8YA']['postal_code'].index[0],5] = 85034
businessDF.iloc[businessDF[businessDF['business_id']=='DmyS9b7ykIOo7XwYt5I9wg']['postal_code'].index[0],5] = 85034
businessDF.iloc[businessDF[businessDF['business_id']=='NOUYmgX2Hl2BlhqsWCUAyg']['postal_code'].index[0],5] = 85339

In [88]:
businessDF[businessDF['business_id']=='Rut5I04WZ2Hm2GEyDwk8YA']

business_id                        name             address  \
5109  Rut5I04WZ2Hm2GEyDwk8YA  Dick Clark's Bar and Grill  Sky Harbor Airport   

         city state  postal_code  latitude  longitude  stars  review_count  \
5109  Phoenix    AZ        85034     33.45    -112.07    1.5            13   

     AgesAllowed Alcohol Ambience_casual Ambience_classy Ambience_divey  \
5109           0       2               0               0              0   

     Ambience_hipster Ambience_intimate Ambience_romantic Ambience_touristy  \
5109                0                 0                 0                 0   

     Ambience_trendy Ambience_upscale BikeParking BusinessAcceptsCreditCards  \
5109               0                0           0                          1   

     BusinessParking_garage BusinessParking_lot BusinessParking_street  \
5109                      0                   0                      0   

     BusinessParking_valet BusinessParking_validated  \
5109                     0                         0   

     DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
5109                              0                               0   

     DietaryRestrictions_halal DietaryRestrictions_kosher  \
5109                         0                          0   

     DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
5109                            0                         0   

     DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
5109                              0           0         0           1   

     GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
5109                     0                  0                   0   

     GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
5109                  0                     0                 0         0   

     HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
5109     1              0          1              0                 0   

     RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
5109                   0                        1                       2   

     RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
5109                       0                       1                  0   

      Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
5109        0                    1    0                0                 0   

      category_American (New)  category_American (Traditional)  \
5109                        0                                1   

      category_Arabian  category_Arcades  category_Argentine  \
5109                 0                 0                   0   

      category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
5109                  0                              0                      0   

      category_Australian  category_Austrian  category_Bagels  \
5109                    0                  0                0   

      category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
5109                  0                  0              0                  0   

      category_Beer Gardens  category_Beer  category_Belgian  \
5109                      0              0                 0   

      category_Bistros  category_Brasseries  category_Brazilian  \
5109                 0                    0                   0   

      category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
5109                            0                   0                  0   

      category_British  category_Bubble Tea  category_Buffets  \
5109                 0                    0                 0   

      category_Burgers  category_Cafes  category_Cafeteria  \
5109                 0               0                   0   

      category_Cajun/Creole  category_Cambodian  category_Cantonese  \
5109                      0                   0              

In [89]:
businessDF[businessDF['business_id']=='DmyS9b7ykIOo7XwYt5I9wg']

business_id         name                 address     city  \
6658  DmyS9b7ykIOo7XwYt5I9wg  Burger King  3400 E Sky Harbor Blvd  Phoenix   

     state  postal_code   latitude   longitude  stars  review_count  \
6658    AZ        85034  33.435466 -112.007171    2.0             8   

     AgesAllowed Alcohol Ambience_casual Ambience_classy Ambience_divey  \
6658           0       0               0               0              0   

     Ambience_hipster Ambience_intimate Ambience_romantic Ambience_touristy  \
6658                0                 0                 0                 0   

     Ambience_trendy Ambience_upscale BikeParking BusinessAcceptsCreditCards  \
6658               0                0           0                          0   

     BusinessParking_garage BusinessParking_lot BusinessParking_street  \
6658                      0                   0                      0   

     BusinessParking_valet BusinessParking_validated  \
6658                     0                         0   

     DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
6658                              0                               0   

     DietaryRestrictions_halal DietaryRestrictions_kosher  \
6658                         0                          0   

     DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
6658                            0                         0   

     DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
6658                              0           0         0           0   

     GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
6658                     0                  0                   0   

     GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
6658                  0                     0                 0         0   

     HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
6658     0              0          1              0                 0   

     RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
6658                   0                        0                       2   

     RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
6658                       0                       0                  1   

      Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
6658        0                    1    0                0                 0   

      category_American (New)  category_American (Traditional)  \
6658                        0                                0   

      category_Arabian  category_Arcades  category_Argentine  \
6658                 0                 0                   0   

      category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
6658                  0                              0                      0   

      category_Australian  category_Austrian  category_Bagels  \
6658                    0                  0                0   

      category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
6658                  0                  0              0                  0   

      category_Beer Gardens  category_Beer  category_Belgian  \
6658                      0              0                 0   

      category_Bistros  category_Brasseries  category_Brazilian  \
6658                 0                    0                   0   

      category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
6658                            0                   0                  0   

      category_British  category_Bubble Tea  category_Buffets  \
6658                 0                    0                 0   

      category_Burgers  category_Cafes  category_Cafeteria  \
6658                 1               0                   0   

      category_Cajun/Creole  category_Cambodian  category_Cantonese  \
6658                      0                   0                   0   

      c

In [90]:
businessDF[businessDF['business_id']=='NOUYmgX2Hl2BlhqsWCUAyg']

business_id              name             address    city  \
857  NOUYmgX2Hl2BlhqsWCUAyg  Black Bear Diner  3530 W Baseline Rd  Laveen   

    state  postal_code   latitude   longitude  stars  review_count  \
857    AZ        85339  33.378135 -112.136202    4.0            36   

    AgesAllowed Alcohol Ambience_casual Ambience_classy Ambience_divey  \
857           0       1               0               0              0   

    Ambience_hipster Ambience_intimate Ambience_romantic Ambience_touristy  \
857                0                 0                 0                 0   

    Ambience_trendy Ambience_upscale BikeParking BusinessAcceptsCreditCards  \
857               0                0           0                          1   

    BusinessParking_garage BusinessParking_lot BusinessParking_street  \
857                      0                   0                      0   

    BusinessParking_valet BusinessParking_validated  \
857                     0                         0   

    DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
857                              0                               0   

    DietaryRestrictions_halal DietaryRestrictions_kosher  \
857                         0                          0   

    DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
857                            0                         0   

    DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
857                              0           0         0           1   

    GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
857                     0                  0                   1   

    GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
857                  1                     0                 1         0   

    HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
857     0              0          3              0                 0   

    RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
857                   0                        1                       2   

    RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
857                       1                       1                  1   

     Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
857        0                    0    0                0                 0   

     category_American (New)  category_American (Traditional)  \
857                        0                                1   

     category_Arabian  category_Arcades  category_Argentine  \
857                 0                 0                   0   

     category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
857                  0                              0                      0   

     category_Australian  category_Austrian  category_Bagels  \
857                    0                  0                0   

     category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
857                  0                  0              0                  0   

     category_Beer Gardens  category_Beer  category_Belgian  category_Bistros  \
857                      0              0                 0                 0   

     category_Brasseries  category_Brazilian  category_Breakfast & Brunch  \
857                    0                   0                            1   

     category_Breweries  category_Brewpubs  category_British  \
857                   0                  0                 0   

     category_Bubble Tea  category_Buffets  category_Burgers  category_Cafes  \
857                    0                 0                 0               0   

     category_Cafeteria  category_Cajun/Creole  category_Cambodian  \
857                   0                      0                   0   

     category_Cantonese  category_Caribbean  category_Casinos  \
857                   0                   0         

In [91]:
businessDF.iloc[businessDF[businessDF['business_id']=='pgpnvPd3mWxI0O9WYUeLnA']['city'].index[0],3] = 'Glendale'

In [92]:
businessDF[businessDF['business_id']=='pgpnvPd3mWxI0O9WYUeLnA']['city']

4978    Glendale
Name: city, dtype: object

In [93]:
businessDF.iloc[businessDF[businessDF['business_id'] == 'RAUI7uwpMP6dlcHXkavwHg']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'zy6Hzao6lTmuJMZo4BemIg']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '1M0Mo_ctYMTH0CTKgv4RpQ']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'MJoHqF2VIKhBuMzpRnwrZA']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '81XqABPROlu8WIER-soVmA']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'qo4dzAKiwdN44wjexJWH4g']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'LYHSSljEdYktLfk3t1E3vg']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '18NP-qL3VIJEBJGpns7aTw']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '_XgvHKj5Mn8h9q61FrPkNg']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'NOUYmgX2Hl2BlhqsWCUAyg']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '2THWm-2RT0MtkH-BKN6-FQ']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '8jNrbT0weOHH43Lf3Bzyig']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '0n2us6pzfJ4UK9qy1NWYOg']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'mDNh9K4eOIfjiZb1DlV88A']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'jWI_Ykdqcz9QNelFFktBEA']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'gaGhS-nnnjW_i6WwPWH75A']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'E54AvEdLfCFFkCvXmXJ7GA']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '9mAMjgAoXrBwsNKaug-cmQ']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '2CTHVcbajrh24zM-a6aKBg']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'KrCYn8fK6zg5JYu4O6kE2g']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'dGFrCnwIUEdi-zxkwDoezQ']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '3rX4WqckBD2e4Hdeic9wUQ']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'Y-omMxOCDSYd7jbo1PSCig']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'nB0SDknanRBT0b9HDqJv8g']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'Oh1s-LpxUF9HswZ0zhGPPA']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'gOcq978lYnZaaRVGAqF69w']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == 'd2D09qs6bVs6Bjb9WnTIdA']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '0oSWfLMJZnl2HhOc2lQb2g']['city'].index[0],3] = \
businessDF.iloc[businessDF[businessDF['business_id'] == '_8I19IRzDXmMSRES9cEGlw']['city'].index[0],3] = 'Laveen Village'

In [94]:
businessDF[businessDF['business_id'] == 'Oh1s-LpxUF9HswZ0zhGPPA']['city']

5897    Laveen Village
Name: city, dtype: object

In [95]:
businessDF.iloc[businessDF[businessDF['business_id']=='svU7GceMV2PsJe6MLSJWIA']['city'].index[0],3] = 'Mesa'

In [96]:
businessDF[businessDF['business_id']=='svU7GceMV2PsJe6MLSJWIA']

business_id             name          address  city state  \
2545  svU7GceMV2PsJe6MLSJWIA  Jack in the Box  2719 N Power Rd  Mesa    AZ   

      postal_code   latitude   longitude  stars  review_count AgesAllowed  \
2545        85215  33.464139 -111.683294    3.5            10           0   

     Alcohol Ambience_casual Ambience_classy Ambience_divey Ambience_hipster  \
2545       0               0               0              0                0   

     Ambience_intimate Ambience_romantic Ambience_touristy Ambience_trendy  \
2545                 0                 0                 0               0   

     Ambience_upscale BikeParking BusinessAcceptsCreditCards  \
2545                0           1                          1   

     BusinessParking_garage BusinessParking_lot BusinessParking_street  \
2545                      0                   0                      0   

     BusinessParking_valet BusinessParking_validated  \
2545                     0                         0   

     DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
2545                              0                               0   

     DietaryRestrictions_halal DietaryRestrictions_kosher  \
2545                         0                          0   

     DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
2545                            0                         0   

     DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
2545                              0           0         1           1   

     GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
2545                     1                  0                   0   

     GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
2545                  0                     0                 1         0   

     HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
2545     0              0          0              0                 0   

     RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
2545                   0                        1                       1   

     RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
2545                       0                       0                  1   

      Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
2545        0                    0    0                0                 0   

      category_American (New)  category_American (Traditional)  \
2545                        0                                0   

      category_Arabian  category_Arcades  category_Argentine  \
2545                 0                 0                   0   

      category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
2545                  0                              0                      0   

      category_Australian  category_Austrian  category_Bagels  \
2545                    0                  0                0   

      category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
2545                  0                  0              0                  0   

      category_Beer Gardens  category_Beer  category_Belgian  \
2545                      0              0                 0   

      category_Bistros  category_Brasseries  category_Brazilian  \
2545                 0                    0                   0   

      category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
2545                            0                   0                  0   

      category_British  category_Bubble Tea  category_Buffets  \
2545                 0                    0                 0   

      category_Burgers  category_Cafes  category_Cafeteria  \
2545                 0               0                   0   

      category_Cajun/Creole  category_Cambodian  category_Cantonese  \
2545                      0                   0                   0   

      category_Cari

In [97]:
businessDF.iloc[businessDF[businessDF['business_id']=='mhjSXQR9LvL10SSHH6aHIg']['name'].index[0],1] = 'Mole'
businessDF.iloc[businessDF[businessDF['business_id']=='mhjSXQR9LvL10SSHH6aHIg']['city'].index[0],3] = 'Phoenix'

In [98]:
businessDF[businessDF['business_id']=='mhjSXQR9LvL10SSHH6aHIg']

business_id  name                 address     city state  \
6288  mhjSXQR9LvL10SSHH6aHIg  Mole  101 N 1st Ave, Ste 115  Phoenix    AZ   

      postal_code   latitude  longitude  stars  review_count AgesAllowed  \
6288        85003  33.449834  -112.0747    4.5             9           0   

     Alcohol Ambience_casual Ambience_classy Ambience_divey Ambience_hipster  \
6288       0               0               0              0                0   

     Ambience_intimate Ambience_romantic Ambience_touristy Ambience_trendy  \
6288                 0                 0                 0               0   

     Ambience_upscale BikeParking BusinessAcceptsCreditCards  \
6288                0           0                          1   

     BusinessParking_garage BusinessParking_lot BusinessParking_street  \
6288                      0                   0                      0   

     BusinessParking_valet BusinessParking_validated  \
6288                     0                         0   

     DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
6288                              0                               0   

     DietaryRestrictions_halal DietaryRestrictions_kosher  \
6288                         0                          0   

     DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
6288                            0                         0   

     DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
6288                              0           0         0           0   

     GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
6288                     0                  0                   0   

     GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
6288                  0                     0                 0         0   

     HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
6288     0              0          1              0                 0   

     RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
6288                   0                        0                       0   

     RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
6288                       0                       0                  1   

      Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
6288        0                    1    0                0                 0   

      category_American (New)  category_American (Traditional)  \
6288                        0                                0   

      category_Arabian  category_Arcades  category_Argentine  \
6288                 0                 0                   0   

      category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
6288                  0                              0                      0   

      category_Australian  category_Austrian  category_Bagels  \
6288                    0                  0                0   

      category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
6288                  0                  0              1                  1   

      category_Beer Gardens  category_Beer  category_Belgian  \
6288                      0              0                 0   

      category_Bistros  category_Brasseries  category_Brazilian  \
6288                 0                    0                   0   

      category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
6288                            0                   0                  0   

      category_British  category_Bubble Tea  category_Buffets  \
6288                 0                    0                 0   

      category_Burgers  category_Cafes  category_Cafeteria  \
6288                 0               1                   0   

      category_Cajun/Creole  category_Cambodian  category_Cantonese  \
6288                      0                   0                   0   

      category_Caribbea

In [99]:
businessDF.iloc[businessDF[businessDF['business_id']=='0Zu6KcjFJjBpCOjiOa2HvQ']['city'].index[0],3] = 'Scottsdale'
businessDF.iloc[businessDF[businessDF['business_id']=='JvHv4HDT7sU7rMYyDzJuMQ']['city'].index[0],3] = 'Scottsdale'
businessDF.iloc[businessDF[businessDF['business_id']=='Y3aGrZR8QBlj8C2l7oEvDg']['city'].index[0],3] = 'Scottsdale'

In [100]:
businessDF[businessDF['business_id']=='0Zu6KcjFJjBpCOjiOa2HvQ']

business_id                   name  \
5179  0Zu6KcjFJjBpCOjiOa2HvQ  Eat Fit Go Scottsdale   

                           address        city state  postal_code  latitude  \
5179  7135 E Camelback Rd, Ste 152  Scottsdale    AZ        85251  33.50185   

      longitude  stars  review_count AgesAllowed Alcohol Ambience_casual  \
5179 -111.92794    3.0            10           0       0               0   

     Ambience_classy Ambience_divey Ambience_hipster Ambience_intimate  \
5179               0              0                0                 0   

     Ambience_romantic Ambience_touristy Ambience_trendy Ambience_upscale  \
5179                 0                 0               0                0   

     BikeParking BusinessAcceptsCreditCards BusinessParking_garage  \
5179           1                          1                      0   

     BusinessParking_lot BusinessParking_street BusinessParking_valet  \
5179                   0                      0                     0   

     BusinessParking_validated DietaryRestrictions_dairy-free  \
5179                         0                              0   

     DietaryRestrictions_gluten-free DietaryRestrictions_halal  \
5179                               0                         0   

     DietaryRestrictions_kosher DietaryRestrictions_soy-free  \
5179                          0                            0   

     DietaryRestrictions_vegan DietaryRestrictions_vegetarian DogsAllowed  \
5179                         0                              0           0   

     DriveThru GoodForKids GoodForMeal_breakfast GoodForMeal_brunch  \
5179         0           0                     0                  0   

     GoodForMeal_dessert GoodForMeal_dinner GoodForMeal_latenight  \
5179                   0                  0                     0   

     GoodForMeal_lunch HappyHour HasTV Music_no_music NoiseLevel  \
5179                 0         0     0              0          1   

     OutdoorSeating RestaurantsAttire RestaurantsDelivery  \
5179              0                 0                   0   

     RestaurantsGoodForGroups  RestaurantsPriceRange2 RestaurantsReservations  \
5179                        0                       2                       0   

     RestaurantsTableService RestaurantsTakeOut  Smoking WheelchairAccessible  \
5179                       0                  1        0                    0   

     WiFi  category_Afghan  category_African  category_American (New)  \
5179    0                0                 0                        0   

      category_American (Traditional)  category_Arabian  category_Arcades  \
5179                                0                 0                 0   

      category_Argentine  category_Armenian  category_Arts & Entertainment  \
5179                   0                  0                              0   

      category_Asian Fusion  category_Australian  category_Austrian  \
5179                      0                    0                  0   

      category_Bagels  category_Bakeries  category_Barbeque  category_Bars  \
5179                0                  0                  0              0   

      category_Beer Bar  category_Beer Gardens  category_Beer  \
5179                  0                      0              0   

      category_Belgian  category_Bistros  category_Brasseries  \
5179                 0                 0                    0   

      category_Brazilian  category_Breakfast & Brunch  category_Breweries  \
5179                   0                            1                   0   

      category_Brewpubs  category_British  category_Bubble Tea  \
5179                  0                 0                    0   

      category_Buffets  category_Burgers  category_Cafes  category_Cafeteria  \
5179                 0                 0               0                   0   

      category_Cajun/Creole  category_Cambodian  category_Cantonese  \
5179                      0                  

In [101]:
businessDF[businessDF['business_id']=='JvHv4HDT7sU7rMYyDzJuMQ']

business_id             name         address        city  \
757  JvHv4HDT7sU7rMYyDzJuMQ  Beverly on Main  7018 E Main St  Scottsdale   

    state  postal_code  latitude   longitude  stars  review_count AgesAllowed  \
757    AZ        85251  33.49328 -111.929765    4.0           146           0   

    Alcohol Ambience_casual Ambience_classy Ambience_divey Ambience_hipster  \
757       2               0               0              0                0   

    Ambience_intimate Ambience_romantic Ambience_touristy Ambience_trendy  \
757                 0                 0                 0               1   

    Ambience_upscale BikeParking BusinessAcceptsCreditCards  \
757                0           1                          1   

    BusinessParking_garage BusinessParking_lot BusinessParking_street  \
757                      0                   0                      1   

    BusinessParking_valet BusinessParking_validated  \
757                     0                         0   

    DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
757                              0                               0   

    DietaryRestrictions_halal DietaryRestrictions_kosher  \
757                         0                          0   

    DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
757                            0                         0   

    DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
757                              0           0         0           0   

    GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
757                     0                  0                   0   

    GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
757                  0                     1                 0         1   

    HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
757     1              1          1              1                 0   

    RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
757                   0                        1                       2   

    RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
757                       1                       1                  0   

     Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
757        1                    1    1                0                 0   

     category_American (New)  category_American (Traditional)  \
757                        1                                0   

     category_Arabian  category_Arcades  category_Argentine  \
757                 0                 0                   0   

     category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
757                  0                              0                      0   

     category_Australian  category_Austrian  category_Bagels  \
757                    0                  0                0   

     category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
757                  0                  0              1                  0   

     category_Beer Gardens  category_Beer  category_Belgian  category_Bistros  \
757                      0              0                 0                 0   

     category_Brasseries  category_Brazilian  category_Breakfast & Brunch  \
757                    0                   0                            0   

     category_Breweries  category_Brewpubs  category_British  \
757                   0                  0                 0   

     category_Bubble Tea  category_Buffets  category_Burgers  category_Cafes  \
757                    0                 0                 0               0   

     category_Cafeteria  category_Cajun/Creole  category_Cambodian  \
757                   0                      0                   0   

     category_Cantonese  category_Caribbean  category_Casinos  \
757                   0                   0             

In [102]:
businessDF[businessDF['business_id']=='Y3aGrZR8QBlj8C2l7oEvDg']

business_id               name                   address  \
997  Y3aGrZR8QBlj8C2l7oEvDg  The Vig McCormick  7345 N Via Paseo Del Sur   

           city state  postal_code   latitude   longitude  stars  \
997  Scottsdale    AZ        85258  33.543072 -111.905227    4.0   

     review_count AgesAllowed Alcohol Ambience_casual Ambience_classy  \
997           292           0       2               0               0   

    Ambience_divey Ambience_hipster Ambience_intimate Ambience_romantic  \
997              0                0                 0                 0   

    Ambience_touristy Ambience_trendy Ambience_upscale BikeParking  \
997                 0               0                0           1   

    BusinessAcceptsCreditCards BusinessParking_garage BusinessParking_lot  \
997                          1                      0                   1   

    BusinessParking_street BusinessParking_valet BusinessParking_validated  \
997                      0                     0                         0   

    DietaryRestrictions_dairy-free DietaryRestrictions_gluten-free  \
997                              0                               0   

    DietaryRestrictions_halal DietaryRestrictions_kosher  \
997                         0                          0   

    DietaryRestrictions_soy-free DietaryRestrictions_vegan  \
997                            0                         0   

    DietaryRestrictions_vegetarian DogsAllowed DriveThru GoodForKids  \
997                              0           0         0           0   

    GoodForMeal_breakfast GoodForMeal_brunch GoodForMeal_dessert  \
997                     0                  1                   0   

    GoodForMeal_dinner GoodForMeal_latenight GoodForMeal_lunch HappyHour  \
997                  1                     0                 1         1   

    HasTV Music_no_music NoiseLevel OutdoorSeating RestaurantsAttire  \
997     1              1          1              1                 0   

    RestaurantsDelivery RestaurantsGoodForGroups  RestaurantsPriceRange2  \
997                   0                        1                       2   

    RestaurantsReservations RestaurantsTableService RestaurantsTakeOut  \
997                       0                       1                  1   

     Smoking WheelchairAccessible WiFi  category_Afghan  category_African  \
997        0                    1    1                0                 0   

     category_American (New)  category_American (Traditional)  \
997                        1                                0   

     category_Arabian  category_Arcades  category_Argentine  \
997                 0                 0                   0   

     category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
997                  0                              0                      0   

     category_Australian  category_Austrian  category_Bagels  \
997                    0                  0                0   

     category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
997                  0                  0              1                  1   

     category_Beer Gardens  category_Beer  category_Belgian  category_Bistros  \
997                      0              1                 0                 0   

     category_Brasseries  category_Brazilian  category_Breakfast & Brunch  \
997                    0                   0                            0   

     category_Breweries  category_Brewpubs  category_British  \
997                   0                  0                 0   

     category_Bubble Tea  category_Buffets  category_Burgers  category_Cafes  \
997                    0                 0                 0               0   

     category_Cafeteria  category_Cajun/Creole  category_Cambodian  \
997                   0                      0                   0   

     category_Cantonese  category_Caribbean  category_Casinos  \
997                   0       

In [103]:
businessDF.iloc[businessDF[businessDF['business_id']=='boFrQQWEXyNe79kQ_DOjYA']['city'].index[0],3] = 'Sun City West'

In [104]:
businessDF[businessDF['business_id']=='boFrQQWEXyNe79kQ_DOjYA']['city']

4056    Sun City West
Name: city, dtype: object

In [105]:
businessDF[businessDF['business_id']=='WGQpjj6eA6mRBxp4XST6Ig']

business_id                name  \
4104  WGQpjj6eA6mRBxp4XST6Ig  White Tank Library   

                             address     city state  postal_code   latitude  \
4104  20304 W White Tank Mountain Rd  Waddell    AZ        85355  33.567088   

       longitude  stars  review_count AgesAllowed Alcohol Ambience_casual  \
4104 -112.497764    4.5            21           0       0               0   

     Ambience_classy Ambience_divey Ambience_hipster Ambience_intimate  \
4104               0              0                0                 0   

     Ambience_romantic Ambience_touristy Ambience_trendy Ambience_upscale  \
4104                 0                 0               0                0   

     BikeParking BusinessAcceptsCreditCards BusinessParking_garage  \
4104           0                          0                      0   

     BusinessParking_lot BusinessParking_street BusinessParking_valet  \
4104                   0                      0                     0   

     BusinessParking_validated DietaryRestrictions_dairy-free  \
4104                         0                              0   

     DietaryRestrictions_gluten-free DietaryRestrictions_halal  \
4104                               0                         0   

     DietaryRestrictions_kosher DietaryRestrictions_soy-free  \
4104                          0                            0   

     DietaryRestrictions_vegan DietaryRestrictions_vegetarian DogsAllowed  \
4104                         0                              0           0   

     DriveThru GoodForKids GoodForMeal_breakfast GoodForMeal_brunch  \
4104         0           0                     0                  0   

     GoodForMeal_dessert GoodForMeal_dinner GoodForMeal_latenight  \
4104                   0                  0                     0   

     GoodForMeal_lunch HappyHour HasTV Music_no_music NoiseLevel  \
4104                 0         0     0              0          1   

     OutdoorSeating RestaurantsAttire RestaurantsDelivery  \
4104              0                 0                   0   

     RestaurantsGoodForGroups  RestaurantsPriceRange2 RestaurantsReservations  \
4104                        0                       0                       0   

     RestaurantsTableService RestaurantsTakeOut  Smoking WheelchairAccessible  \
4104                       0                  0        0                    0   

     WiFi  category_Afghan  category_African  category_American (New)  \
4104    1                0                 0                        0   

      category_American (Traditional)  category_Arabian  category_Arcades  \
4104                                0                 0                 0   

      category_Argentine  category_Armenian  category_Arts & Entertainment  \
4104                   0                  0                              0   

      category_Asian Fusion  category_Australian  category_Austrian  \
4104                      0                    0                  0   

      category_Bagels  category_Bakeries  category_Barbeque  category_Bars  \
4104                0                  0                  0              0   

      category_Beer Bar  category_Beer Gardens  category_Beer  \
4104                  0                      0              0   

      category_Belgian  category_Bistros  category_Brasseries  \
4104                 0                 0                    0   

      category_Brazilian  category_Breakfast & Brunch  category_Breweries  \
4104                   0                            0                   0   

      category_Brewpubs  category_British  category_Bubble Tea  \
4104                  0                 0                    0   

      category_Buffets  category_Burgers  category_Cafes  category_Cafeteria  \
4104                 0                 0               0                   0   

      category_Cajun/Creole  category_Cambodian  category_Cantonese  \
4104                      0                   0  

In [106]:
businessDF= businessDF.drop(4104, axis=0)

In [107]:
businessDF[businessDF['business_id']=='WGQpjj6eA6mRBxp4XST6Ig']

Empty DataFrame
Columns: [business_id, name, address, city, state, postal_code, latitude, longitude, stars, review_count, AgesAllowed, Alcohol, Ambience_casual, Ambience_classy, Ambience_divey, Ambience_hipster, Ambience_intimate, Ambience_romantic, Ambience_touristy, Ambience_trendy, Ambience_upscale, BikeParking, BusinessAcceptsCreditCards, BusinessParking_garage, BusinessParking_lot, BusinessParking_street, BusinessParking_valet, BusinessParking_validated, DietaryRestrictions_dairy-free, DietaryRestrictions_gluten-free, DietaryRestrictions_halal, DietaryRestrictions_kosher, DietaryRestrictions_soy-free, DietaryRestrictions_vegan, DietaryRestrictions_vegetarian, DogsAllowed, DriveThru, GoodForKids, GoodForMeal_breakfast, GoodForMeal_brunch, GoodForMeal_dessert, GoodForMeal_dinner, GoodForMeal_latenight, GoodForMeal_lunch, HappyHour, HasTV, Music_no_music, NoiseLevel, OutdoorSeating, RestaurantsAttire, RestaurantsDelivery, RestaurantsGoodForGroups, RestaurantsPriceRange2, RestaurantsReservations, RestaurantsTableService, RestaurantsTakeOut, Smoking, WheelchairAccessible, WiFi, category_Afghan, category_African, category_American (New), category_American (Traditional), category_Arabian, category_Arcades, category_Argentine, category_Armenian, category_Arts & Entertainment, category_Asian Fusion, category_Australian, category_Austrian, category_Bagels, category_Bakeries, category_Barbeque, category_Bars, category_Beer Bar, category_Beer Gardens, category_Beer, category_Belgian, category_Bistros, category_Brasseries, category_Brazilian, category_Breakfast & Brunch, category_Breweries, category_Brewpubs, category_British, category_Bubble Tea, category_Buffets, category_Burgers, category_Cafes, category_Cafeteria, category_Cajun/Creole, category_Cambodian, category_Cantonese, category_Caribbean, category_Casinos, category_Caterers, category_Cheesesteaks, category_Chicken Shop, category_Chicken Wings, ...]
Index: []

In [108]:
businessDF= businessDF.drop(4973, axis=0)

In [109]:
businessDF[businessDF['business_id']=='82bfom6b5BQlnnd4m3wwew']

Empty DataFrame
Columns: [business_id, name, address, city, state, postal_code, latitude, longitude, stars, review_count, AgesAllowed, Alcohol, Ambience_casual, Ambience_classy, Ambience_divey, Ambience_hipster, Ambience_intimate, Ambience_romantic, Ambience_touristy, Ambience_trendy, Ambience_upscale, BikeParking, BusinessAcceptsCreditCards, BusinessParking_garage, BusinessParking_lot, BusinessParking_street, BusinessParking_valet, BusinessParking_validated, DietaryRestrictions_dairy-free, DietaryRestrictions_gluten-free, DietaryRestrictions_halal, DietaryRestrictions_kosher, DietaryRestrictions_soy-free, DietaryRestrictions_vegan, DietaryRestrictions_vegetarian, DogsAllowed, DriveThru, GoodForKids, GoodForMeal_breakfast, GoodForMeal_brunch, GoodForMeal_dessert, GoodForMeal_dinner, GoodForMeal_latenight, GoodForMeal_lunch, HappyHour, HasTV, Music_no_music, NoiseLevel, OutdoorSeating, RestaurantsAttire, RestaurantsDelivery, RestaurantsGoodForGroups, RestaurantsPriceRange2, RestaurantsReservations, RestaurantsTableService, RestaurantsTakeOut, Smoking, WheelchairAccessible, WiFi, category_Afghan, category_African, category_American (New), category_American (Traditional), category_Arabian, category_Arcades, category_Argentine, category_Armenian, category_Arts & Entertainment, category_Asian Fusion, category_Australian, category_Austrian, category_Bagels, category_Bakeries, category_Barbeque, category_Bars, category_Beer Bar, category_Beer Gardens, category_Beer, category_Belgian, category_Bistros, category_Brasseries, category_Brazilian, category_Breakfast & Brunch, category_Breweries, category_Brewpubs, category_British, category_Bubble Tea, category_Buffets, category_Burgers, category_Cafes, category_Cafeteria, category_Cajun/Creole, category_Cambodian, category_Cantonese, category_Caribbean, category_Casinos, category_Caterers, category_Cheesesteaks, category_Chicken Shop, category_Chicken Wings, ...]
Index: []

In [110]:
businessDF[businessDF['name']=='Desert Finds']

Empty DataFrame
Columns: [business_id, name, address, city, state, postal_code, latitude, longitude, stars, review_count, AgesAllowed, Alcohol, Ambience_casual, Ambience_classy, Ambience_divey, Ambience_hipster, Ambience_intimate, Ambience_romantic, Ambience_touristy, Ambience_trendy, Ambience_upscale, BikeParking, BusinessAcceptsCreditCards, BusinessParking_garage, BusinessParking_lot, BusinessParking_street, BusinessParking_valet, BusinessParking_validated, DietaryRestrictions_dairy-free, DietaryRestrictions_gluten-free, DietaryRestrictions_halal, DietaryRestrictions_kosher, DietaryRestrictions_soy-free, DietaryRestrictions_vegan, DietaryRestrictions_vegetarian, DogsAllowed, DriveThru, GoodForKids, GoodForMeal_breakfast, GoodForMeal_brunch, GoodForMeal_dessert, GoodForMeal_dinner, GoodForMeal_latenight, GoodForMeal_lunch, HappyHour, HasTV, Music_no_music, NoiseLevel, OutdoorSeating, RestaurantsAttire, RestaurantsDelivery, RestaurantsGoodForGroups, RestaurantsPriceRange2, RestaurantsReservations, RestaurantsTableService, RestaurantsTakeOut, Smoking, WheelchairAccessible, WiFi, category_Afghan, category_African, category_American (New), category_American (Traditional), category_Arabian, category_Arcades, category_Argentine, category_Armenian, category_Arts & Entertainment, category_Asian Fusion, category_Australian, category_Austrian, category_Bagels, category_Bakeries, category_Barbeque, category_Bars, category_Beer Bar, category_Beer Gardens, category_Beer, category_Belgian, category_Bistros, category_Brasseries, category_Brazilian, category_Breakfast & Brunch, category_Breweries, category_Brewpubs, category_British, category_Bubble Tea, category_Buffets, category_Burgers, category_Cafes, category_Cafeteria, category_Cajun/Creole, category_Cambodian, category_Cantonese, category_Caribbean, category_Casinos, category_Caterers, category_Cheesesteaks, category_Chicken Shop, category_Chicken Wings, ...]
Index: []

In [115]:
businessDF.iloc[businessDF[businessDF['business_id']=='gZGsReG0VeX4uKViHTB9EQ']['latitude'].index[0],6] = 33.5959024
businessDF.iloc[businessDF[businessDF['business_id']=='gZGsReG0VeX4uKViHTB9EQ']['longitude'].index[0],7] = -112.1531041

In [116]:
businessDF[businessDF['business_id']=='gZGsReG0VeX4uKViHTB9EQ']

business_id        name           address      city state  \
4737  gZGsReG0VeX4uKViHTB9EQ  Don Rubens  4323 W Cactus Rd  Glendale    AZ   

      postal_code   latitude   longitude  stars  review_count  AgesAllowed  \
4737        85304  33.595902 -112.153104    3.0             4            0   

      Alcohol  Ambience_casual  Ambience_classy  Ambience_divey  \
4737        0                0                0               0   

      Ambience_hipster  Ambience_intimate  Ambience_romantic  \
4737                 0                  0                  0   

      Ambience_touristy  Ambience_trendy  Ambience_upscale  BikeParking  \
4737                  0                0                 0            0   

      BusinessAcceptsCreditCards  BusinessParking_garage  BusinessParking_lot  \
4737                           1                       0                    0   

      BusinessParking_street  BusinessParking_valet  \
4737                       0                      0   

      BusinessParking_validated  DietaryRestrictions_dairy-free  \
4737                          0                               0   

      DietaryRestrictions_gluten-free  DietaryRestrictions_halal  \
4737                                0                          0   

      DietaryRestrictions_kosher  DietaryRestrictions_soy-free  \
4737                           0                             0   

      DietaryRestrictions_vegan  DietaryRestrictions_vegetarian  DogsAllowed  \
4737                          0                               0            0   

      DriveThru  GoodForKids  GoodForMeal_breakfast  GoodForMeal_brunch  \
4737          0            0                      0                   0   

      GoodForMeal_dessert  GoodForMeal_dinner  GoodForMeal_latenight  \
4737                    0                   0                      0   

      GoodForMeal_lunch  HappyHour  HasTV  Music_no_music  NoiseLevel  \
4737                  0          0      0               0           1   

      OutdoorSeating  RestaurantsAttire  RestaurantsDelivery  \
4737               0                  0                    0   

      RestaurantsGoodForGroups  RestaurantsPriceRange2  \
4737                         0                       2   

      RestaurantsReservations  RestaurantsTableService  RestaurantsTakeOut  \
4737                        0                        0                   0   

      Smoking  WheelchairAccessible  WiFi  category_Afghan  category_African  \
4737        0                     0     0                0                 0   

      category_American (New)  category_American (Traditional)  \
4737                        0                                0   

      category_Arabian  category_Arcades  category_Argentine  \
4737                 0                 0                   0   

      category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
4737                  0                              0                      0   

      category_Australian  category_Austrian  category_Bagels  \
4737                    0                  0                0   

      category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
4737                  0                  0              0                  0   

      category_Beer Gardens  category_Beer  category_Belgian  \
4737                      0              0                 0   

      category_Bistros  category_Brasseries  category_Brazilian  \
4737                 0                    0                   0   

      category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
4737                            0                   0                  0   

      category_British  category_Bubble Tea  category_Buffets  \
4737                 0                    0                 0   

      category_Burgers  category_Cafes  category_Cafeteria  \
4737                 0               0                   0   

      category_Cajun/Creole  category_Cambodian  ca

In [117]:
businessDF[businessDF['business_id']=='kkEqZmVvVkgmCaOqE13mDg']['name']

655    #1 Sushi
Name: name, dtype: object

In [118]:
businessDF.iloc[businessDF[businessDF['business_id']=='kkEqZmVvVkgmCaOqE13mDg'].index[0],1]= '1 Sushi'

In [119]:
businessDF[businessDF['business_id']=='kkEqZmVvVkgmCaOqE13mDg']

business_id     name            address     city state  \
655  kkEqZmVvVkgmCaOqE13mDg  1 Sushi  9617 N Metro Pkwy  Phoenix    AZ   

     postal_code   latitude   longitude  stars  review_count  AgesAllowed  \
655        85051  33.582652 -112.118526    4.0            55            0   

     Alcohol  Ambience_casual  Ambience_classy  Ambience_divey  \
655        0                1                0               0   

     Ambience_hipster  Ambience_intimate  Ambience_romantic  \
655                 0                  0                  0   

     Ambience_touristy  Ambience_trendy  Ambience_upscale  BikeParking  \
655                  0                0                 0            1   

     BusinessAcceptsCreditCards  BusinessParking_garage  BusinessParking_lot  \
655                           1                       0                    0   

     BusinessParking_street  BusinessParking_valet  BusinessParking_validated  \
655                       0                      0                          0   

     DietaryRestrictions_dairy-free  DietaryRestrictions_gluten-free  \
655                               0                                0   

     DietaryRestrictions_halal  DietaryRestrictions_kosher  \
655                          0                           0   

     DietaryRestrictions_soy-free  DietaryRestrictions_vegan  \
655                             0                          0   

     DietaryRestrictions_vegetarian  DogsAllowed  DriveThru  GoodForKids  \
655                               0            0          0            1   

     GoodForMeal_breakfast  GoodForMeal_brunch  GoodForMeal_dessert  \
655                      0                   0                    0   

     GoodForMeal_dinner  GoodForMeal_latenight  GoodForMeal_lunch  HappyHour  \
655                   1                      0                  1          0   

     HasTV  Music_no_music  NoiseLevel  OutdoorSeating  RestaurantsAttire  \
655      1               0           1               0                  0   

     RestaurantsDelivery  RestaurantsGoodForGroups  RestaurantsPriceRange2  \
655                    0                         1                       1   

     RestaurantsReservations  RestaurantsTableService  RestaurantsTakeOut  \
655                        0                        0                   1   

     Smoking  WheelchairAccessible  WiFi  category_Afghan  category_African  \
655        0                     0     0                0                 0   

     category_American (New)  category_American (Traditional)  \
655                        0                                0   

     category_Arabian  category_Arcades  category_Argentine  \
655                 0                 0                   0   

     category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
655                  0                              0                      1   

     category_Australian  category_Austrian  category_Bagels  \
655                    0                  0                0   

     category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
655                  0                  0              0                  0   

     category_Beer Gardens  category_Beer  category_Belgian  category_Bistros  \
655                      0              0                 0                 0   

     category_Brasseries  category_Brazilian  category_Breakfast & Brunch  \
655                    0                   0                            0   

     category_Breweries  category_Brewpubs  category_British  \
655                   0                  0                 0   

     category_Bubble Tea  category_Buffets  category_Burgers  category_Cafes  \
655                    0                 0                 0               0   

     category_Cafeteria  category_Cajun/Creole  category_Cambodian  \
655                   0                      0                   0   

     category_Cantonese  category_Caribbe

In [120]:
businessDF[businessDF['business_id']=='ysaGG0hm7-ug-IuRd-8_ew']['name']

1308    #1 Fried Rice
Name: name, dtype: object

In [121]:
businessDF.iloc[businessDF[businessDF['business_id']=='ysaGG0hm7-ug-IuRd-8_ew'].index[0],1]= '1 Fried Rice'

In [122]:
businessDF[businessDF['business_id']=='ysaGG0hm7-ug-IuRd-8_ew']

business_id          name              address      city  \
1308  ysaGG0hm7-ug-IuRd-8_ew  1 Fried Rice  9310 W Van Buren St  Tolleson   

     state  postal_code   latitude   longitude  stars  review_count  \
1308    AZ        85353  33.450589 -112.260298    3.5            38   

      AgesAllowed  Alcohol  Ambience_casual  Ambience_classy  Ambience_divey  \
1308            0        0                0                0               0   

      Ambience_hipster  Ambience_intimate  Ambience_romantic  \
1308                 0                  0                  0   

      Ambience_touristy  Ambience_trendy  Ambience_upscale  BikeParking  \
1308                  0                0                 0            1   

      BusinessAcceptsCreditCards  BusinessParking_garage  BusinessParking_lot  \
1308                           1                       0                    0   

      BusinessParking_street  BusinessParking_valet  \
1308                       0                      0   

      BusinessParking_validated  DietaryRestrictions_dairy-free  \
1308                          0                               0   

      DietaryRestrictions_gluten-free  DietaryRestrictions_halal  \
1308                                0                          0   

      DietaryRestrictions_kosher  DietaryRestrictions_soy-free  \
1308                           0                             0   

      DietaryRestrictions_vegan  DietaryRestrictions_vegetarian  DogsAllowed  \
1308                          0                               0            0   

      DriveThru  GoodForKids  GoodForMeal_breakfast  GoodForMeal_brunch  \
1308          0            1                      0                   0   

      GoodForMeal_dessert  GoodForMeal_dinner  GoodForMeal_latenight  \
1308                    0                   0                      0   

      GoodForMeal_lunch  HappyHour  HasTV  Music_no_music  NoiseLevel  \
1308                  0          0      0               0           1   

      OutdoorSeating  RestaurantsAttire  RestaurantsDelivery  \
1308               0                  0                    0   

      RestaurantsGoodForGroups  RestaurantsPriceRange2  \
1308                         1                       1   

      RestaurantsReservations  RestaurantsTableService  RestaurantsTakeOut  \
1308                        0                        0                   1   

      Smoking  WheelchairAccessible  WiFi  category_Afghan  category_African  \
1308        0                     0     0                0                 0   

      category_American (New)  category_American (Traditional)  \
1308                        0                                0   

      category_Arabian  category_Arcades  category_Argentine  \
1308                 0                 0                   0   

      category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
1308                  0                              0                      0   

      category_Australian  category_Austrian  category_Bagels  \
1308                    0                  0                0   

      category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
1308                  0                  0              0                  0   

      category_Beer Gardens  category_Beer  category_Belgian  \
1308                      0              0                 0   

      category_Bistros  category_Brasseries  category_Brazilian  \
1308                 0                    0                   0   

      category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
1308                            0                   0                  0   

      category_British  category_Bubble Tea  category_Buffets  \
1308                 0                    0                 0   

      category_Burgers  category_Cafes  category_Cafeteria  \
1308                 0               0                   0   

      category_Cajun/Creole  category_Cam

In [123]:
businessDF[businessDF['business_id']=='4z-QW_f3RwCAxHB5fd58TA']['name']

6801    #1Brothers Pizza
Name: name, dtype: object

In [124]:
businessDF.iloc[businessDF[businessDF['business_id']=='4z-QW_f3RwCAxHB5fd58TA'].index[0],1]= '1 Brother\'s Pizza'

In [125]:
businessDF[businessDF['business_id']=='4z-QW_f3RwCAxHB5fd58TA']

business_id               name                       address  \
6801  4z-QW_f3RwCAxHB5fd58TA  1 Brother's Pizza  16995 W Greenway Rd, Ste 104   

          city state  postal_code  latitude   longitude  stars  review_count  \
6801  Surprise    AZ        85388  33.62366 -112.424707    3.0            60   

      AgesAllowed  Alcohol  Ambience_casual  Ambience_classy  Ambience_divey  \
6801            0        1                1                0               0   

      Ambience_hipster  Ambience_intimate  Ambience_romantic  \
6801                 0                  0                  0   

      Ambience_touristy  Ambience_trendy  Ambience_upscale  BikeParking  \
6801                  0                0                 0            1   

      BusinessAcceptsCreditCards  BusinessParking_garage  BusinessParking_lot  \
6801                           1                       0                    1   

      BusinessParking_street  BusinessParking_valet  \
6801                       0                      0   

      BusinessParking_validated  DietaryRestrictions_dairy-free  \
6801                          0                               0   

      DietaryRestrictions_gluten-free  DietaryRestrictions_halal  \
6801                                0                          0   

      DietaryRestrictions_kosher  DietaryRestrictions_soy-free  \
6801                           0                             0   

      DietaryRestrictions_vegan  DietaryRestrictions_vegetarian  DogsAllowed  \
6801                          0                               0            0   

      DriveThru  GoodForKids  GoodForMeal_breakfast  GoodForMeal_brunch  \
6801          0            1                      0                   0   

      GoodForMeal_dessert  GoodForMeal_dinner  GoodForMeal_latenight  \
6801                    0                   1                      0   

      GoodForMeal_lunch  HappyHour  HasTV  Music_no_music  NoiseLevel  \
6801                  1          0      1               0           0   

      OutdoorSeating  RestaurantsAttire  RestaurantsDelivery  \
6801               0                  0                    0   

      RestaurantsGoodForGroups  RestaurantsPriceRange2  \
6801                         1                       2   

      RestaurantsReservations  RestaurantsTableService  RestaurantsTakeOut  \
6801                        0                        0                   1   

      Smoking  WheelchairAccessible  WiFi  category_Afghan  category_African  \
6801        0                     1     0                0                 0   

      category_American (New)  category_American (Traditional)  \
6801                        0                                0   

      category_Arabian  category_Arcades  category_Argentine  \
6801                 0                 0                   0   

      category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
6801                  0                              0                      0   

      category_Australian  category_Austrian  category_Bagels  \
6801                    0                  0                0   

      category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
6801                  0                  0              0                  0   

      category_Beer Gardens  category_Beer  category_Belgian  \
6801                      0              0                 0   

      category_Bistros  category_Brasseries  category_Brazilian  \
6801                 0                    0                   0   

      category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
6801                            0                   0                  0   

      category_British  category_Bubble Tea  category_Buffets  \
6801                 0                    0                 0   

      category_Burgers  category_Cafes  category_Cafeteria  \
6801                 0               0                   0   

      category_

In [126]:
businessDF.iloc[businessDF[businessDF['business_id']=='gWY94C5EgNClUOwqJXrBGg'].index[0],1] = '1 Brother\'s Pizza'

In [127]:
businessDF[businessDF['business_id']=='gWY94C5EgNClUOwqJXrBGg']

business_id               name                       address  \
7229  gWY94C5EgNClUOwqJXrBGg  1 Brother's Pizza  11435 W Buckeye Rd, Ste A104   

          city state  postal_code   latitude   longitude  stars  review_count  \
7229  Avondale    AZ        85323  33.434305 -112.304677    4.0            52   

      AgesAllowed  Alcohol  Ambience_casual  Ambience_classy  Ambience_divey  \
7229            0        1                1                0               0   

      Ambience_hipster  Ambience_intimate  Ambience_romantic  \
7229                 0                  0                  0   

      Ambience_touristy  Ambience_trendy  Ambience_upscale  BikeParking  \
7229                  0                0                 0            0   

      BusinessAcceptsCreditCards  BusinessParking_garage  BusinessParking_lot  \
7229                           1                       0                    0   

      BusinessParking_street  BusinessParking_valet  \
7229                       1                      0   

      BusinessParking_validated  DietaryRestrictions_dairy-free  \
7229                          0                               0   

      DietaryRestrictions_gluten-free  DietaryRestrictions_halal  \
7229                                0                          0   

      DietaryRestrictions_kosher  DietaryRestrictions_soy-free  \
7229                           0                             0   

      DietaryRestrictions_vegan  DietaryRestrictions_vegetarian  DogsAllowed  \
7229                          0                               0            0   

      DriveThru  GoodForKids  GoodForMeal_breakfast  GoodForMeal_brunch  \
7229          0            1                      0                   0   

      GoodForMeal_dessert  GoodForMeal_dinner  GoodForMeal_latenight  \
7229                    0                   1                      0   

      GoodForMeal_lunch  HappyHour  HasTV  Music_no_music  NoiseLevel  \
7229                  1          0      1               0           1   

      OutdoorSeating  RestaurantsAttire  RestaurantsDelivery  \
7229               0                  0                    0   

      RestaurantsGoodForGroups  RestaurantsPriceRange2  \
7229                         1                       1   

      RestaurantsReservations  RestaurantsTableService  RestaurantsTakeOut  \
7229                        0                        1                   1   

      Smoking  WheelchairAccessible  WiFi  category_Afghan  category_African  \
7229        0                     1     0                0                 0   

      category_American (New)  category_American (Traditional)  \
7229                        0                                0   

      category_Arabian  category_Arcades  category_Argentine  \
7229                 0                 0                   0   

      category_Armenian  category_Arts & Entertainment  category_Asian Fusion  \
7229                  0                              0                      0   

      category_Australian  category_Austrian  category_Bagels  \
7229                    0                  0                0   

      category_Bakeries  category_Barbeque  category_Bars  category_Beer Bar  \
7229                  0                  0              0                  0   

      category_Beer Gardens  category_Beer  category_Belgian  \
7229                      0              0                 0   

      category_Bistros  category_Brasseries  category_Brazilian  \
7229                 0                    0                   0   

      category_Breakfast & Brunch  category_Breweries  category_Brewpubs  \
7229                            0                   0                  0   

      category_British  category_Bubble Tea  category_Buffets  \
7229                 0                    0                 0   

      category_Burgers  category_Cafes  category_Cafeteria  \
7229                 0               0                   0   

      categor

For confirmation and cross verification running the loop again to determine if any missing values' needs to be handled.

In [128]:
for colmn in businessDF.columns.values:
    print('Column name: ',colmn)
    print('No of Unique values: ',businessDF[colmn].nunique())
    print('Unique values: ',businessDF[colmn].unique())
    print('NaN count: ',businessDF[colmn].isnull().sum())
    if(colmn not in ['business_id','name','neighborhood','address','city','state','postal_code','latitude','longitude',
                     'stars','review_count']):
        print('Attribute counts:\n',businessDF[colmn].value_counts(),'\n')
    print('++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++')

Column name:  business_id
No of Unique values:  7365
Unique values:  ['rDMptJYWtnMhpQu_rRXHng' '1WBkAuQg81kokZIPMpn9Zg'
 'iPa__LOhse-hobC2Xmp-Kw' ... '5zva2MTtB5IX6TaoVLL-NA'
 'Gr-2oBg4XyduSKbvnE-i9g' 'UdEmYOnk2iJDY9lpEPAlJQ']
NaN count:  0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  name
No of Unique values:  4168
Unique values:  ["McDonald's" 'Charr An American Burger Bar' 'Little Caesars Pizza' ...
 "Yin's Chinese Resturant" 'Zorbas Grill'
 'Salt & Lime Modern Mexican Grill']
NaN count:  0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  address
No of Unique values:  6720
Unique values:  ['719 E Thunderbird Rd' '777 E Thunderbird Rd, Ste 107'
 '1635 E Camelback Rd' ... '1950 W Indian School Rd'
 '9397 E Shea Blvd, Ste 115' '590 N Alma School Rd, Ste 35']
NaN count:  85
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  city
No of Unique values:  31
U

NaN count:  0
Attribute counts:
 0    7362
1       3
Name: DietaryRestrictions_halal, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  DietaryRestrictions_kosher
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7362
1       3
Name: DietaryRestrictions_kosher, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  DietaryRestrictions_soy-free
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7362
1       3
Name: DietaryRestrictions_soy-free, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  DietaryRestrictions_vegan
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7353
1      12
Name: DietaryRestrictions_vegan, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  

Column name:  category_German
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7360
1       5
Name: category_German, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Gluten-Free
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7217
1     148
Name: category_Gluten-Free, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Greek
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7241
1     124
Name: category_Greek, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column name:  category_Grocery
No of Unique values:  2
Unique values:  [0 1]
NaN count:  0
Attribute counts:
 0    7303
1      62
Name: category_Grocery, dtype: int64 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Column

In [129]:
businessDF.shape

(7365, 235)

Our restaurant dataframe has now finally 7365 businesses with 235 unique attributes.

Exporting the dataframe to a 'csv' file for Recommendation and Tableau EDA.

In [130]:
import csv

In [131]:
businessDF.to_csv('AZ_Restaurant_Final_Clean_Data.csv', header=True, encoding='utf-8', index=False)

## The resulting file will be used for further EDA using univariate/bivariate analysis and NLP/Recommendation processing. 